// Generated by scripts/generate_rebuild_contracts.py. Do not edit.
// Flexible JSON responses remain unknown/records; no invented response fields.
export const OPENAPI_SHA256 = "039bc054241b4ca3328cce4981854decf8d35f129e477cdb956545a5da4476f9" as const

export interface Components {
  "AIConfigSave": { "expected_revision": number; "max_tokens": number; "temperature": number; "text": Components["ProviderConfig"]; "timeout_seconds": number; "vision": Components["ProviderConfig"] }
  "AbnormalUniverseRunCreate": { "board_filters"?: Array<("main" | "gem" | "star" | "beijing" | "st")>; "cooling_days"?: number; "date_from": string; "date_to": string; "include_warnings"?: boolean; "markets"?: Array<("sh" | "sz" | "bj")>; "max_bars"?: number; "scan_mode"?: ("snapshot" | "full") } & Record<string, unknown>
  "AccountCreate": { "name": string } & Record<string, unknown>
  "AkShareDailySync": { "end_date": string; "mode"?: ("full" | "incremental"); "start_date": string; "symbol": string } & Record<string, unknown>
  "AnalysisCreate": { "block_size"?: number; "iterations"?: number; "name"?: string; "plan_date"?: (string | null); "seed"?: number; "source_run_id": string }
  "AttachmentConfirm": { "acknowledge_limitations"?: boolean; "expected_preview_sha256": string; "expected_revision": number; "files": Array<Components["AttachmentFile"]> }
  "AttachmentFile": { "content_base64": string; "filename": string; "source_key": string }
  "AttachmentSelection": { "expected_revision": number; "files": Array<Components["AttachmentFile"]> }
  "B1ParamsInput": { "amp_limit_10cm"?: number; "amp_limit_20cm"?: number; "chg_limit"?: number; "kdj_j_upper"?: number; "vol_ratio"?: number }
  "B1RunCreate": { "as_of_date": string; "b1_params"?: Components["B1ParamsInput"]; "dataset_ids": Array<string> } & Record<string, unknown>
  "B1UniverseRunCreate": { "as_of_date": string; "b1_params"?: Components["B1ParamsInput"]; "markets"?: Array<("sh" | "sz")>; "max_bars"?: number } & Record<string, unknown>
  "BackfillCreate": { "dataset_ids": Array<string>; "end_date": string; "event_profile_id"?: (string | null); "event_profile_revision"?: (number | null); "expected_preview_sha256": string; "start_date": string; "strict"?: boolean; "window_days"?: Array<number> }
  "BackfillPreview": { "dataset_ids": Array<string>; "end_date": string; "event_profile_id"?: (string | null); "event_profile_revision"?: (number | null); "start_date": string; "strict"?: boolean; "window_days"?: Array<number> }
  "BacktestCreate": { "advanced_analysis"?: boolean; "analysis_iterations"?: number; "analysis_seed"?: number; "dataset_id": string; "event_profile_id"?: (string | null); "event_profile_revision"?: (number | null); "fee_config"?: (Record<string, string> | null); "holding_bars"?: number; "initial_capital"?: string; "max_position_pct"?: string; "params"?: Record<string, string>; "stop_loss_pct"?: string; "strategy_id": string; "strict"?: boolean; "take_profit_pct"?: string; "trailing_stop_pct"?: string }
  "BasketCreate": { "fees"?: (Record<string, string> | null); "holding_bars"?: number; "holding_mode"?: ("legacy_signal_anchor" | "complete_overnights"); "name": string; "notes"?: string; "quantity"?: number; "run_ids"?: (Array<string> | null); "scan_date"?: (string | null); "scan_id"?: (string | null); "selection"?: ("union" | "intersection") } & Record<string, unknown>
  "BasketDeleteBatch": { "items": Array<Components["BasketDeleteItem"]> } & Record<string, unknown>
  "BasketDeleteItem": { "expected_revision": number; "id": string } & Record<string, unknown>
  "BasketEvaluationCreate": { "as_of_date": string; "expected_revision": number; "forward_datasets"?: Record<string, string>; "strict"?: boolean } & Record<string, unknown>
  "BasketUpdate": { "expected_revision": number; "fees"?: (Record<string, string> | null); "holding_bars"?: (number | null); "holding_mode"?: (("legacy_signal_anchor" | "complete_overnights") | null); "name"?: (string | null); "notes"?: (string | null); "quantity"?: (number | null); "run_ids"?: (Array<string> | null) } & Record<string, unknown>
  "Body_import_report_api_v1_research_portfolio_reports_import_post": { "file": Blob } & Record<string, unknown>
  "Body_import_report_api_v1_research_reports_import_post": { "file": Blob } & Record<string, unknown>
  "Body_post_daily_attachment_api_v1_accounts__account_id__daily_reviews__day__attachments_post": { "file": Blob } & Record<string, unknown>
  "Body_preview_api_v1_research_legacy_reports_preview_post": { "file": Blob } & Record<string, unknown>
  "Body_preview_backup_api_v1_system_backups_preview_post": { "file": Blob } & Record<string, unknown>
  "Body_restore_backup_api_v1_system_backups_restore_new_post": { "destination": string; "expected_fingerprint": string; "file": Blob } & Record<string, unknown>
  "Body_save_api_v1_research_legacy_reports_import_post": { "acknowledge_limitations"?: boolean; "expected_preview_sha256": string; "file": Blob; "mode": string } & Record<string, unknown>
  "BrowserSessionData": { "csrf_token": string; "expires_in_seconds": number } & Record<string, unknown>
  "BrowserSessionResponse": { "data": Components["BrowserSessionData"] } & Record<string, unknown>
  "CalendarDay": { "date": string; "is_open": boolean }
  "CalendarImport": { "days": Array<Components["CalendarDay"]>; "end_date": string; "expected_revision": number; "source": string; "start_date": string }
  "CashFlowCreate": { "amount": string; "flow_date": string; "kind": ("initial" | "deposit" | "withdraw"); "note"?: string } & Record<string, unknown>
  "Confirm": { "account_name"?: string; "acknowledge_limitations"?: boolean; "content_base64": string; "expected_preview_sha256": string; "filename": string; "mode"?: ("archive_only" | "new_real_account") }
  "ConnectionTest": { "channel"?: ("text" | "vision"); "config_revision": number }
  "CopyCommit": { "destination": string; "expected_fingerprint": string }
  "CopyRequest": { "destination": string }
  "CopyScores": { "dimensions": Array<string>; "expected_revision": number }
  "DailyInspirationRequest": { "day": string } & Record<string, unknown>
  "DailyReviewSave": { "decision_review"?: string; "expected_revision": number; "market_observation"?: string; "mistakes"?: string; "next_market_forecast"?: string; "next_position_plan"?: string; "next_position_rehearsal"?: Array<Record<string, (string | number)>>; "next_risk_plan"?: string; "next_target_date"?: (string | null); "next_watchlist"?: Array<Record<string, string>>; "overall_summary"?: string; "reflection"?: string; "tags"?: Array<string>; "title"?: string; "tomorrow_plan"?: string } & Record<string, unknown>
  "DirectoryPick": Record<string, never>
  "EmptyAction": Record<string, never>
  "EventProfileAction": { "expected_active_revision": number; "expected_revision": number } & Record<string, unknown>
  "EventProfileSave": { "expected_revision"?: (number | null); "profile": Record<string, unknown> } & Record<string, unknown>
  "ExportSelection": { "columns"?: (Array<string> | null); "dataset_ids"?: (Array<string> | null); "stage"?: (string | null) }
  "FetchRequest": { "date": string; "symbol": string }
  "FunnelConfig": { "mode"?: ("strict" | "loose"); "step1"?: Components["Step1"]; "step2"?: Components["Step2"]; "step3"?: Components["Step3"]; "step4"?: Components["Step4"] } & Record<string, unknown>
  "HTTPValidationError": { "detail"?: Array<Components["ValidationError"]> } & Record<string, unknown>
  "Import": { "expected_revision": number; "preview_sha256": string; "value": Record<string, unknown> }
  "InspirationCardCreate": { "content": string; "tags"?: Array<string> } & Record<string, unknown>
  "LadderRunCreate": { "board_filters"?: Array<("main" | "gem" | "star" | "beijing" | "st")>; "dataset_ids": Array<string>; "date_from": string; "date_to": string; "historical_min_boards"?: number; "recent_days"?: number } & Record<string, unknown>
  "LadderUniverseRunCreate": { "board_filters"?: Array<("main" | "gem" | "star" | "beijing" | "st")>; "date_from": string; "date_to": string; "historical_min_boards"?: number; "markets"?: Array<("sh" | "sz" | "bj")>; "max_bars"?: number; "recent_days"?: number } & Record<string, unknown>
  "MarketBarInput": { "amount"?: (string | null); "available_at"?: (string | null); "close": string; "event_date": string; "high": string; "low": string; "open": string; "volume": number } & Record<string, unknown>
  "MarketCacheImport": { "provider": ("akshare" | "baostock"); "symbol": string } & Record<string, unknown>
  "MarketDatasetImport": { "adjustment"?: "none"; "bars": Array<Components["MarketBarInput"]>; "symbol": string } & Record<string, unknown>
  "MatrixPoolRunCreate": { "params"?: Record<string, string>; "source_run_id": string; "strict"?: boolean } & Record<string, unknown>
  "NewsRequest": { "age_hours"?: (24 | 48 | 72); "as_of_at"?: (string | null); "date_from"?: (string | null); "date_to"?: (string | null); "provider"?: ("auto" | "eastmoney" | "google_rss"); "query"?: string }
  "OnlineBatchSync": { "end_date": string; "mode"?: ("full" | "incremental"); "provider"?: ("auto" | "akshare" | "baostock"); "provider_order"?: Array<("akshare" | "baostock")>; "start_date": string; "symbols": Array<string> } & Record<string, unknown>
  "OnlineDailySync": { "end_date": string; "mode"?: ("full" | "incremental"); "provider"?: ("auto" | "akshare" | "baostock"); "provider_order"?: Array<("akshare" | "baostock")>; "start_date": string; "symbol": string } & Record<string, unknown>
  "ParameterProposal": { "account_id"?: (string | null); "expected_revision": number; "params"?: (Record<string, unknown> | null); "preset_id": string; "source_ai_run_id"?: (string | null) }
  "PendingTradeBatch": { "items": Array<Components["PendingTradeBatchItem"]> } & Record<string, unknown>
  "PendingTradeBatchItem": { "acknowledge_duplicate"?: boolean; "expected_revision": number; "id": string } & Record<string, unknown>
  "PendingTradeConfirm": { "acknowledge_duplicate"?: boolean; "expected_revision": number } & Record<string, unknown>
  "PeriodReviewSave": { "expected_revision": number; "sections"?: Record<string, string> } & Record<string, unknown>
  "PlateauCreate": { "axes": Record<string, unknown>; "base_run_id": string; "expected_preview_sha256": string; "max_points"?: number; "name": string; "sample_points"?: number; "sampling_mode"?: ("grid" | "lhs"); "seed"?: (number | null) }
  "PlateauPreview": { "axes": Record<string, unknown>; "base_run_id": string; "max_points"?: number; "sample_points"?: number; "sampling_mode"?: ("grid" | "lhs"); "seed"?: (number | null) }
  "PortfolioCreate": { "config"?: Record<string, unknown>; "dataset_ids": Array<string>; "end_date"?: (string | null); "event_profile_id"?: (string | null); "event_profile_revision"?: (number | null); "expected_preview_sha256": string; "mode": ("matrix_raw_s1_s9" | "traditional_runtime14" | "aligned_wyckoff_events"); "name": string; "params"?: Record<string, unknown>; "start_date"?: (string | null); "strategy_id"?: (string | null) }
  "PortfolioPreview": { "config"?: Record<string, unknown>; "dataset_ids": Array<string>; "end_date"?: (string | null); "event_profile_id"?: (string | null); "event_profile_revision"?: (number | null); "mode": ("matrix_raw_s1_s9" | "traditional_runtime14" | "aligned_wyckoff_events"); "params"?: Record<string, unknown>; "start_date"?: (string | null); "strategy_id"?: (string | null) }
  "PortfolioReportCreate": { "analysis_run_id"?: (string | null); "portfolio_run_id": string; "title": string }
  "PresetImport": { "current_params"?: Record<string, unknown>; "share_code": string }
  "PresetSave": { "expected_revision"?: (number | null); "favorite"?: boolean; "name": string; "params": Record<string, unknown>; "strategy_id": string }
  "ProbeRequest": { "end_date": string; "start_date": string; "symbol": string }
  "Promotion": { "account_name": string; "expected_revision": number }
  "PromotionConfirm": { "account_name": string; "acknowledge_limitations"?: boolean; "expected_preview_sha256": string; "expected_revision": number }
  "PromptContext": { "account_date"?: (string | null); "artifact_sources"?: Array<Record<string, unknown>>; "dataset_ids"?: Array<string>; "decision_at"?: (string | null); "manual_text"?: string; "run_ids"?: Array<string>; "strict"?: boolean }
  "PromptRequest": { "channel"?: ("text" | "vision"); "config_revision": number; "context"?: Components["PromptContext"]; "expected_input_sha256"?: (string | null); "message": string; "template_id"?: (string | null); "template_revision"?: (number | null) }
  "ProposalApply": { "expected_proposal_hash": string; "expected_revision": number }
  "ProviderConfig": { "base_url": string; "model": string; "secret_ref": string }
  "RealFeeConfigUpdate": { "config": Record<string, string>; "expected_version": number } & Record<string, unknown>
  "RehearsalPreview": { "baseline_source"?: ("snapshot" | "ledger"); "dataset_ids"?: Array<string>; "expected_baseline_sha256": string; "rows"?: Array<Components["RehearsalRow"]>; "target_date"?: (string | null) }
  "RehearsalRow": { "code": string; "name"?: string; "note"?: string; "price"?: (string | null); "qty": number }
  "ReportCreate": { "backtest_run_id": string; "title": string }
  "ResearchRunCreate": { "dataset_id": string; "decision_at": string; "event_profile_id"?: (string | null); "event_profile_revision"?: (number | null); "params"?: Record<string, string>; "strategy_id": string; "strict"?: boolean } & Record<string, unknown>
  "Reset": { "expected_revision": number; "preview_sha256": string }
  "ReviewScoresSave": { "comment"?: string; "expected_revision": number; "scope": ("daily" | "trade" | "t_group"); "scores"?: Record<string, Components["ScoreEntrySave"]>; "trade_ids"?: Array<string> } & Record<string, unknown>
  "Revision": { "expected_revision": number }
  "RoundNoteSave": { "expected_revision": number; "summary"?: string } & Record<string, unknown>
  "SaveRequest": { "expected_revision": number; "state": Record<string, unknown> }
  "ScanLocations": Record<string, never>
  "ScoreEntrySave": { "comment"?: string; "final"?: (number | null) } & Record<string, unknown>
  "ScreenerDatasetInput": { "dataset_id": string; "float_shares"?: (number | null); "float_shares_as_of_date"?: (string | null); "float_shares_source_sha256"?: (string | null) } & Record<string, unknown>
  "ScreenerRunCreate": { "as_of_date": string; "config"?: Components["FunnelConfig"]; "datasets": Array<Components["ScreenerDatasetInput"]>; "return_window_days"?: number } & Record<string, unknown>
  "SectorFlowRunCreate": { "daily_top_n"?: number; "date_from": string; "date_to": string; "flow_window"?: number; "max_bars"?: number } & Record<string, unknown>
  "SelectLocation": { "path": string }
  "SessionCreate": { "account_id"?: (string | null); "title"?: string }
  "SimAccountCreate": { "config"?: (Record<string, string> | null); "initial_capital": string; "name": string; "start_date": string } & Record<string, unknown>
  "SimConfigUpdate": { "config": Record<string, string>; "expected_version": number } & Record<string, unknown>
  "SimDraftBatchItem": { "expected_revision": number; "id": string } & Record<string, unknown>
  "SimDraftBatchSubmit": { "drafts": Array<Components["SimDraftBatchItem"]>; "expected_config_version": number; "expected_wallet_revision": number } & Record<string, unknown>
  "SimDraftCreate": { "limit_price": string; "quantity": number; "source_run_id": string } & Record<string, unknown>
  "SimDraftSizing": { "limit_price": string; "mode": ("lots" | "amount" | "cash_percent"); "value": string } & Record<string, unknown>
  "SimDraftUpdate": { "expected_revision": number; "limit_price": string; "quantity": number } & Record<string, unknown>
  "SimFillCreate": { "expected_revision": number; "fill_date": string; "fill_price": string } & Record<string, unknown>
  "SimFillTagsSave": { "emotion_tag_id"?: (string | null); "expected_revision": number; "reason_tag_ids"?: Array<string> } & Record<string, unknown>
  "SimMarketAdvance": { "datasets"?: Record<string, string>; "expected_wallet_revision": number; "to_date": string } & Record<string, unknown>
  "SimOpenMatch": { "dataset_id": string; "expected_revision": number } & Record<string, unknown>
  "SimOrderCreate": { "limit_price": string; "quantity": number; "side": ("buy" | "sell"); "signal_date": string; "submit_date": string; "symbol": string } & Record<string, unknown>
  "SimRecoveryActivate": { "expected_wallet_revision": number } & Record<string, unknown>
  "SimReset": { "expected_wallet_revision": number; "reset_config"?: boolean; "start_date": string } & Record<string, unknown>
  "SimReviewTagCreate": { "name": string; "type": ("emotion" | "reason") } & Record<string, unknown>
  "SimSettle": { "to_date": string } & Record<string, unknown>
  "SnapshotPositionInput": { "market_value": string; "name"?: string; "quantity": number; "symbol": string } & Record<string, unknown>
  "SnapshotSave": { "available_cash"?: (string | null); "expected_revision": number; "note"?: string; "position_value"?: (string | null); "positions"?: (Array<Components["SnapshotPositionInput"]> | null); "snap_date": string; "total_assets": string } & Record<string, unknown>
  "StateRequest": { "state": Record<string, unknown> }
  "Step1": { "amount_threshold"?: number; "amplitude_threshold"?: number; "rank_start"?: number; "top_n"?: number; "turnover_threshold"?: number } & Record<string, unknown>
  "Step2": { "allow_b_trend"?: boolean; "max_price_vs_ma20"?: number; "max_pullback_days"?: number; "min_ma10_above_ma20_days"?: number; "min_ma5_above_ma10_days"?: number; "require_above_ma20"?: boolean; "retrace_max"?: number; "retrace_min"?: number } & Record<string, unknown>
  "Step3": { "allow_blowoff_top"?: boolean; "allow_degraded"?: boolean; "allow_divergence_5d"?: boolean; "allow_upper_shadow_risk"?: boolean; "max_pullback_volume_ratio"?: number; "min_up_down_volume_ratio"?: number; "min_vol_slope20"?: number } & Record<string, unknown>
  "Step4": { "allow_degraded"?: boolean; "allowed_theme_stages"?: Array<("发酵中" | "高潮" | "退潮" | "Unknown")>; "final_top_n"?: number; "min_ai_confidence"?: number } & Record<string, unknown>
  "StockAnnotationSave": { "decision": ("保留" | "排除"); "expected_revision": number; "notes"?: string; "stage": ("Early" | "Mid" | "Late"); "start_date": string; "trend_class": ("A" | "A_B" | "B" | "Unknown") } & Record<string, unknown>
  "StrategyScanCreate": { "as_of_date"?: (string | null); "dataset_ids": Array<string>; "date_from"?: (string | null); "date_to"?: (string | null); "event_profile_id"?: (string | null); "event_profile_revision"?: (number | null); "signal_context"?: (Components["StrategySignalContext"] | null); "strategies": Array<Components["StrategyScanItem"]>; "strict"?: boolean }
  "StrategyScanItem": { "params"?: Record<string, (string | number | number | boolean)>; "strategy_id": string }
  "StrategySignalContext": { "candidate_path"?: ("legacy_store" | "legacy_tdx"); "universe_mode"?: ("strategy_filtered" | "full_market"); "window_days"?: number }
  "SupplementConfirm": { "acknowledge_limitations"?: boolean; "expected_preview_sha256": string; "expected_revision": number; "secret_refs"?: Record<string, string>; "selected_keys"?: Array<string> }
  "SupplementSelection": { "expected_revision": number; "secret_refs"?: Record<string, string>; "selected_keys"?: Array<string> }
  "SwitchAction": { "expected_fingerprint": string; "verification_id": string }
  "SwitchPreview": { "destination": string }
  "TargetConfigUpdate": { "expected_version": number; "multiplier": string; "node_count": number } & Record<string, unknown>
  "TdxDayImport": { "symbol": string } & Record<string, unknown>
  "TdxUniverseRunCreate": { "as_of_date": string; "config"?: Components["FunnelConfig"]; "markets"?: Array<("sh" | "sz" | "bj")>; "max_bars"?: number; "return_window_days"?: number } & Record<string, unknown>
  "TemplateCreate": { "content": string; "name": string }
  "TemplateSave": { "content": string; "expected_revision": number; "name": string }
  "TradeCreate": { "fee"?: string; "fee_mode"?: ("manual" | "auto"); "name"?: string; "note"?: string; "price": string; "quantity": number; "side": ("buy" | "sell"); "symbol": string; "trade_date": string } & Record<string, unknown>
  "TradeUpdate": { "expected_revision": number; "fee"?: string; "fee_mode"?: ("manual" | "auto"); "name"?: string; "note"?: string; "price": string; "quantity": number; "side": ("buy" | "sell"); "symbol": string; "trade_date": string } & Record<string, unknown>
  "TrendLeaderRunCreate": { "board_filters"?: Array<("main" | "gem" | "star" | "beijing" | "st")>; "daily_top_n"?: number; "dataset_ids": Array<string>; "date_from": string; "date_to": string; "min_amount_avg"?: number; "window_days"?: number } & Record<string, unknown>
  "TrendUniverseRunCreate": { "board_filters"?: Array<("main" | "gem" | "star" | "beijing" | "st")>; "daily_top_n"?: number; "date_from": string; "date_to": string; "markets"?: Array<("sh" | "sz" | "bj")>; "max_bars"?: number; "min_amount_avg"?: number; "window_days"?: number } & Record<string, unknown>
  "Upload": { "account_name"?: string; "content_base64": string; "filename": string; "mode"?: ("archive_only" | "new_real_account") }
  "ValidationError": { "loc": Array<(string | number)>; "msg": string; "type": string } & Record<string, unknown>
  "ValuationRunCreate": { "scenarios": Array<Components["ValuationScenarioInput"]>; "symbol"?: string } & Record<string, unknown>
  "ValuationScenarioInput": { "actual_cap_yi"?: (number | string | null); "base_pe": number; "earnings_yi": (number | string); "growth_rate_pct": number; "index_points": number; "label": string; "sentiment_coef": number } & Record<string, unknown>
  "WalkForwardCreate": { "axes": Record<string, unknown>; "base_run_id": string; "expected_preview_sha256": string; "gap_bars"?: number; "initial_train_bars"?: number; "max_folds"?: number; "max_points"?: number; "min_train_trades"?: number; "name": string; "sample_points"?: number; "sampling_mode"?: ("grid" | "lhs"); "seed"?: (number | null); "test_bars"?: number; "warmup_bars"?: number }
  "WalkForwardPreview": { "axes": Record<string, unknown>; "base_run_id": string; "gap_bars"?: number; "initial_train_bars"?: number; "max_folds"?: number; "max_points"?: number; "min_train_trades"?: number; "sample_points"?: number; "sampling_mode"?: ("grid" | "lhs"); "seed"?: (number | null); "test_bars"?: number; "warmup_bars"?: number }
  "trade_app__api__ai_context_routes__Save": { "expected_revision": number; "items": Array<Record<string, unknown>> }
  "trade_app__api__portfolio_experiment_routes__Create": { "axes": Record<string, unknown>; "base_run_id": string; "expected_preview_sha256": string; "max_points"?: number; "name": string; "sample_points"?: number; "sampling_mode"?: ("grid" | "lhs"); "seed"?: number }
  "trade_app__api__portfolio_experiment_routes__Preview": { "axes": Record<string, unknown>; "base_run_id": string; "max_points"?: number; "sample_points"?: number; "sampling_mode"?: ("grid" | "lhs"); "seed"?: number }
  "trade_app__api__portfolio_walk_forward_routes__Create": { "axes": Record<string, unknown>; "base_run_id": string; "expected_preview_sha256": string; "gap_bars"?: number; "initial_train_bars"?: number; "max_folds"?: number; "max_points"?: number; "min_train_cycles"?: number; "name": string; "sample_points"?: number; "sampling_mode"?: ("grid" | "lhs"); "seed"?: number; "test_bars"?: number }
  "trade_app__api__portfolio_walk_forward_routes__Preview": { "axes": Record<string, unknown>; "base_run_id": string; "gap_bars"?: number; "initial_train_bars"?: number; "max_folds"?: number; "max_points"?: number; "min_train_cycles"?: number; "sample_points"?: number; "sampling_mode"?: ("grid" | "lhs"); "seed"?: number; "test_bars"?: number }
  "trade_app__api__settings_routes__Save": { "expected_revision": number; "value": Record<string, unknown> }
}

export interface Operations {
  "/accounts": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["AccountCreate"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/analytics": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/accounts/{account_id}/analytics/retry": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/asset-estimate/{day}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "dataset_id"?: Array<string>; "decision_at": string; "strict"?: boolean } }
  }
  "/accounts/{account_id}/cash-flows": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["CashFlowCreate"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/cash-flows/{flow_id}": {
    "delete": { requestBody: undefined; response: unknown; query: { "expected_revision": number } }
  }
  "/accounts/{account_id}/daily-reviews": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "limit"?: number } }
  }
  "/accounts/{account_id}/daily-reviews/{day}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "put": { requestBody: Components["DailyReviewSave"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/daily-reviews/{day}/attachments": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["Body_post_daily_attachment_api_v1_accounts__account_id__daily_reviews__day__attachments_post"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/daily-reviews/{day}/scores": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "put": { requestBody: Components["ReviewScoresSave"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/exports/account.xlsx": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/exports/performance.pdf": {
    "get": { requestBody: undefined; response: unknown; query: { "date_basis"?: ("buy" | "sell"); "date_from"?: (string | null); "date_to"?: (string | null); "kind"?: ("daily" | "weekly" | "monthly"); "limit"?: number } }
  }
  "/accounts/{account_id}/exports/performance.xlsx": {
    "get": { requestBody: undefined; response: unknown; query: { "date_basis"?: ("buy" | "sell"); "date_from"?: (string | null); "date_to"?: (string | null); "kind"?: ("daily" | "weekly" | "monthly"); "limit"?: number } }
  }
  "/accounts/{account_id}/exports/performance/{table}.csv": {
    "get": { requestBody: undefined; response: unknown; query: { "date_basis"?: ("buy" | "sell"); "date_from"?: (string | null); "date_to"?: (string | null); "kind"?: ("daily" | "weekly" | "monthly"); "limit"?: number } }
  }
  "/accounts/{account_id}/exports/review/{kind}/{key}.md": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/exports/review/{kind}/{key}.pdf": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/exports/{kind}.csv": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/fee-preview": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "fee"?: string; "fee_mode": string; "price": string; "quantity": number; "side": string } }
    "post": { requestBody: Components["TradeCreate"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/fee-settings": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "put": { requestBody: Components["RealFeeConfigUpdate"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/pending-trades": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["TradeCreate"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/pending-trades/confirm-batch": {
    "post": { requestBody: Components["PendingTradeBatch"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/pending-trades/{pending_id}": {
    "put": { requestBody: Components["TradeUpdate"]; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: { "expected_revision": number } }
  }
  "/accounts/{account_id}/pending-trades/{pending_id}/confirm": {
    "post": { requestBody: Components["PendingTradeConfirm"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/performance": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "kind"?: string; "limit"?: number } }
  }
  "/accounts/{account_id}/period-reviews/{kind}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/accounts/{account_id}/period-reviews/{kind}/{period_key}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "put": { requestBody: Components["PeriodReviewSave"]; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: { "expected_revision": number } }
  }
  "/accounts/{account_id}/plan-comparison/{day}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/accounts/{account_id}/planning/{day}/baseline": {
    "get": { requestBody: undefined; response: unknown; query: { "source"?: ("snapshot" | "ledger") } }
  }
  "/accounts/{account_id}/planning/{day}/preview": {
    "post": { requestBody: Components["RehearsalPreview"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/review-attachments/{attachment_id}": {
    "delete": { requestBody: undefined; response: unknown; query: { "expected_revision": number } }
  }
  "/accounts/{account_id}/review-attachments/{attachment_id}/content": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/review-gaps": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/accounts/{account_id}/review-reminders": {
    "get": { requestBody: undefined; response: unknown; query: { "limit"?: number } }
  }
  "/accounts/{account_id}/review-scores/{sheet_id}/copy-ai-to-final": {
    "post": { requestBody: Components["CopyScores"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/round-notes": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/accounts/{account_id}/round-notes/{round_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "put": { requestBody: Components["RoundNoteSave"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/snapshots": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/accounts/{account_id}/snapshots/{day}": {
    "put": { requestBody: Components["SnapshotSave"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/target-config": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "put": { requestBody: Components["TargetConfigUpdate"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/trades": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["TradeCreate"]; response: unknown; query: Record<string, never> }
  }
  "/accounts/{account_id}/trades/{trade_id}": {
    "put": { requestBody: Components["TradeUpdate"]; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: { "expected_revision": number } }
  }
  "/ai/config": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "put": { requestBody: Components["AIConfigSave"]; response: unknown; query: Record<string, never> }
  }
  "/ai/context-sources": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/ai/generations": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "account_id"?: (string | null) } }
    "post": { requestBody: Record<string, unknown>; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/ai/generations/preview": {
    "post": { requestBody: Record<string, unknown>; response: Record<string, unknown>; query: { "account_id"?: (string | null) } }
  }
  "/ai/generations/{generation_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "account_id"?: (string | null) } }
    "put": { requestBody: Record<string, unknown>; response: unknown; query: { "account_id"?: (string | null) } }
    "delete": { requestBody: undefined; response: unknown; query: { "account_id"?: (string | null); "expected_revision": number } }
  }
  "/ai/generations/{generation_id}/accept": {
    "post": { requestBody: Record<string, unknown>; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/ai/generations/{generation_id}/audit": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "account_id"?: (string | null) } }
  }
  "/ai/generations/{generation_id}/finalize": {
    "post": { requestBody: Record<string, unknown>; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/ai/generations/{generation_id}/reject": {
    "post": { requestBody: Record<string, unknown>; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/ai/generations/{generation_id}/retract": {
    "post": { requestBody: Record<string, unknown>; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/ai/quick-prompts": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "put": { requestBody: Components["trade_app__api__ai_context_routes__Save"]; response: unknown; query: Record<string, never> }
  }
  "/ai/quick-prompts/history": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/ai/runs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "account_id"?: (string | null) } }
  }
  "/ai/runs/{run_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "account_id"?: (string | null) } }
  }
  "/ai/runs/{run_id}/cancel": {
    "post": { requestBody: undefined; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/ai/runs/{run_id}/stream": {
    "post": { requestBody: undefined; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/ai/sessions": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "account_id"?: (string | null) } }
    "post": { requestBody: Components["SessionCreate"]; response: unknown; query: Record<string, never> }
  }
  "/ai/sessions/{session_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "account_id"?: (string | null) } }
    "delete": { requestBody: undefined; response: unknown; query: { "account_id"?: (string | null); "expected_revision": number } }
  }
  "/ai/sessions/{session_id}/preview": {
    "post": { requestBody: Components["PromptRequest"]; response: Record<string, unknown>; query: { "account_id"?: (string | null) } }
  }
  "/ai/sessions/{session_id}/runs": {
    "post": { requestBody: Components["PromptRequest"]; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/ai/templates": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["TemplateCreate"]; response: unknown; query: Record<string, never> }
  }
  "/ai/templates/{template_id}": {
    "put": { requestBody: Components["TemplateSave"]; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: { "expected_revision": number } }
  }
  "/ai/test-connection": {
    "post": { requestBody: Components["ConnectionTest"]; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/ai/usage": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "account_id"?: (string | null) } }
  }
  "/backtests": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["BacktestCreate"]; response: unknown; query: Record<string, never> }
  }
  "/backtests/{run_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/backtests/{run_id}/cancel": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/backtests/{run_id}/export.xlsx": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/backtests/{run_id}/retry": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/backtests/{run_id}/trades.{kind}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/backups/export": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/insights/cards": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["InspirationCardCreate"]; response: unknown; query: Record<string, never> }
  }
  "/insights/cards/{card_id}": {
    "delete": { requestBody: undefined; response: unknown; query: { "expected_revision": number } }
  }
  "/insights/daily": {
    "post": { requestBody: Components["DailyInspirationRequest"]; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "post": { requestBody: Components["Confirm"]; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/preview": {
    "post": { requestBody: Components["Upload"]; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}/attachments": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}/attachments/apply": {
    "post": { requestBody: Components["AttachmentConfirm"]; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}/attachments/preview": {
    "post": { requestBody: Components["AttachmentSelection"]; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}/export.json": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}/promote": {
    "post": { requestBody: Components["PromotionConfirm"]; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}/promotion-preview": {
    "post": { requestBody: Components["Promotion"]; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}/simulation/apply": {
    "post": { requestBody: Components["PromotionConfirm"]; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}/simulation/preview": {
    "post": { requestBody: Components["Promotion"]; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}/supplements": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}/supplements/apply": {
    "post": { requestBody: Components["SupplementConfirm"]; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}/supplements/history": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/legacy-imports/{import_id}/supplements/preview": {
    "post": { requestBody: Components["SupplementSelection"]; response: unknown; query: Record<string, never> }
  }
  "/market/akshare-sync": {
    "post": { requestBody: Components["AkShareDailySync"]; response: unknown; query: Record<string, never> }
  }
  "/market/annotations": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/market/annotations/{symbol}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "put": { requestBody: Components["StockAnnotationSave"]; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: { "expected_revision": number } }
  }
  "/market/cache-import": {
    "post": { requestBody: Components["MarketCacheImport"]; response: unknown; query: Record<string, never> }
  }
  "/market/close": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "dataset_id": string; "day": string } }
  }
  "/market/datasets": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["MarketDatasetImport"]; response: unknown; query: Record<string, never> }
  }
  "/market/datasets/{dataset_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/market/diagnostics": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "verify"?: boolean } }
  }
  "/market/intraday/capabilities": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/market/intraday/fetch": {
    "post": { requestBody: Components["FetchRequest"]; response: unknown; query: Record<string, never> }
  }
  "/market/intraday/snapshots": {
    "get": { requestBody: undefined; response: unknown; query: { "date"?: (string | null); "symbol": string } }
  }
  "/market/intraday/snapshots/{identifier}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/market/news": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "age_hours"?: number; "as_of_at"?: (string | null); "date_from"?: (string | null); "date_to"?: (string | null); "provider"?: string; "query"?: string } }
  }
  "/market/news/refresh": {
    "post": { requestBody: Components["NewsRequest"]; response: unknown; query: Record<string, never> }
  }
  "/market/online-sync": {
    "post": { requestBody: Components["OnlineDailySync"]; response: unknown; query: Record<string, never> }
  }
  "/market/providers": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/market/providers/tdx/locations": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/market/providers/tdx/scan": {
    "post": { requestBody: Components["ScanLocations"]; response: unknown; query: Record<string, never> }
  }
  "/market/providers/tdx/select": {
    "post": { requestBody: Components["SelectLocation"]; response: unknown; query: Record<string, never> }
  }
  "/market/providers/{provider}/probe": {
    "post": { requestBody: Components["ProbeRequest"]; response: unknown; query: Record<string, never> }
  }
  "/market/sync-jobs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["OnlineBatchSync"]; response: unknown; query: Record<string, never> }
  }
  "/market/sync-jobs/{job_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/market/sync-jobs/{job_id}/cancel": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/market/sync-jobs/{job_id}/retry-failed": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/market/tdx-float-shares": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "symbol": Array<string> } }
  }
  "/market/tdx-import": {
    "post": { requestBody: Components["TdxDayImport"]; response: unknown; query: Record<string, never> }
  }
  "/market/tdx-intraday": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "day": string; "symbol": string } }
  }
  "/market/trading-calendar": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "put": { requestBody: Components["CalendarImport"]; response: unknown; query: Record<string, never> }
  }
  "/market/trading-calendar/audit": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/market/trading-calendar/plan-date": {
    "get": { requestBody: undefined; response: unknown; query: { "target_date"?: (string | null); "written_on": string } }
  }
  "/research/abnormal-runs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/abnormal-runs/{run_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/b1-runs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["B1RunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/b1-runs/{run_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/b1-runs/{run_id}/exports/{format}": {
    "post": { requestBody: Components["ExportSelection"]; response: unknown; query: Record<string, never> }
  }
  "/research/b1-runs/{run_id}/signals/{symbol}": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/baskets": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "include_deleted"?: boolean; "name"?: (string | null); "strategy_id"?: (string | null) } }
    "post": { requestBody: Components["BasketCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/baskets/delete-batch": {
    "post": { requestBody: Components["BasketDeleteBatch"]; response: unknown; query: Record<string, never> }
  }
  "/research/baskets/{basket_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "include_deleted"?: boolean } }
    "put": { requestBody: Components["BasketUpdate"]; response: unknown; query: Record<string, never> }
  }
  "/research/baskets/{basket_id}/audit": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/baskets/{basket_id}/evaluations": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["BasketEvaluationCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/baskets/{basket_id}/evaluations/{evaluation_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/baskets/{basket_id}/evaluations/{evaluation_id}/export.xlsx": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/baskets/{basket_id}/export.csv": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/baskets/{basket_id}/export.xlsx": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/event-profiles": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["EventProfileSave"]; response: unknown; query: Record<string, never> }
  }
  "/research/event-profiles/{profile_id}": {
    "put": { requestBody: Components["EventProfileSave"]; response: unknown; query: Record<string, never> }
    "delete": { requestBody: Components["EventProfileAction"]; response: unknown; query: Record<string, never> }
  }
  "/research/event-profiles/{profile_id}/apply": {
    "post": { requestBody: Components["EventProfileAction"]; response: unknown; query: Record<string, never> }
  }
  "/research/event-profiles/{profile_id}/history": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/event-store/jobs": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "post": { requestBody: Components["BackfillCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/event-store/jobs/{job_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/event-store/jobs/{job_id}/{action}": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/event-store/preview": {
    "post": { requestBody: Components["BackfillPreview"]; response: unknown; query: Record<string, never> }
  }
  "/research/event-store/records": {
    "get": { requestBody: undefined; response: unknown; query: { "job_id"?: (string | null); "limit"?: number; "offset"?: number; "symbol"?: (string | null); "version_id"?: (string | null) } }
  }
  "/research/event-store/records/{record_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/event-store/stats": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/legacy-reports": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/legacy-reports/import": {
    "post": { requestBody: Components["Body_save_api_v1_research_legacy_reports_import_post"]; response: unknown; query: Record<string, never> }
  }
  "/research/legacy-reports/preview": {
    "post": { requestBody: Components["Body_preview_api_v1_research_legacy_reports_preview_post"]; response: unknown; query: Record<string, never> }
  }
  "/research/legacy-reports/{identifier}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/legacy-reports/{identifier}/export.json": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/legacy-reports/{identifier}/original.bin": {
    "get": { requestBody: undefined; response: unknown; query: { "name"?: (string | null) } }
  }
  "/research/legacy-reports/{identifier}/report.html": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/legacy-reports/{report_id}/plateau.xlsx": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/legacy-reports/{report_id}/trades.{kind}": {
    "get": { requestBody: undefined; response: unknown; query: { "detail_key"?: (string | null) } }
  }
  "/research/limit-up-ladder-runs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["LadderRunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/limit-up-ladder-runs/{run_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/matrix-runs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["MatrixPoolRunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/matrix-runs/{run_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/matrix-runs/{run_id}/signals/{dataset_id}": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/parameter-proposals": {
    "post": { requestBody: Components["ParameterProposal"]; response: unknown; query: Record<string, never> }
  }
  "/research/parameter-proposals/{proposal_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/parameter-proposals/{proposal_id}/apply": {
    "post": { requestBody: Components["ProposalApply"]; response: unknown; query: Record<string, never> }
  }
  "/research/plateaus": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "post": { requestBody: Components["PlateauCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/plateaus/preview": {
    "post": { requestBody: Components["PlateauPreview"]; response: unknown; query: Record<string, never> }
  }
  "/research/plateaus/schema/{base_run_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/plateaus/{experiment_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/plateaus/{experiment_id}/export.json": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/plateaus/{experiment_id}/export.xlsx": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/plateaus/{experiment_id}/points/{point_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/plateaus/{experiment_id}/{action}": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-analyses": {
    "get": { requestBody: undefined; response: unknown; query: { "source_run_id"?: (string | null) } }
    "post": { requestBody: Components["AnalysisCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-analyses/{run_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-analyses/{run_id}/export.json": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-analyses/{run_id}/{action}": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-experiments": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "post": { requestBody: Components["trade_app__api__portfolio_experiment_routes__Create"]; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-experiments/preview": {
    "post": { requestBody: Components["trade_app__api__portfolio_experiment_routes__Preview"]; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-experiments/schema/{source_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-experiments/{identifier}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-experiments/{identifier}/export.json": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-experiments/{identifier}/points/{point_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-experiments/{identifier}/{action}": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-reports": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "post": { requestBody: Components["PortfolioReportCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-reports/import": {
    "post": { requestBody: Components["Body_import_report_api_v1_research_portfolio_reports_import_post"]; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-reports/{report_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-reports/{report_id}/export.xlsx": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-reports/{report_id}/export.zip": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-reports/{report_id}/report.html": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-walk-forwards": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "post": { requestBody: Components["trade_app__api__portfolio_walk_forward_routes__Create"]; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-walk-forwards/preview": {
    "post": { requestBody: Components["trade_app__api__portfolio_walk_forward_routes__Preview"]; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-walk-forwards/{identifier}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-walk-forwards/{identifier}/export.json": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-walk-forwards/{identifier}/tasks/{task_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolio-walk-forwards/{identifier}/{action}": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolios": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "post": { requestBody: Components["PortfolioCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/portfolios/preview": {
    "post": { requestBody: Components["PortfolioPreview"]; response: unknown; query: Record<string, never> }
  }
  "/research/portfolios/schema": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolios/{run_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolios/{run_id}/export.json": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolios/{run_id}/result": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolios/{run_id}/trades.{kind}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/portfolios/{run_id}/{action}": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/presets": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "favorites_only"?: boolean; "strategy_id"?: (string | null) } }
    "post": { requestBody: Components["PresetSave"]; response: unknown; query: Record<string, never> }
  }
  "/research/presets/preview-import": {
    "post": { requestBody: Components["PresetImport"]; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/presets/{preset_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "put": { requestBody: Components["PresetSave"]; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: { "expected_revision": number } }
  }
  "/research/presets/{preset_id}/export": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/presets/{preset_id}/history": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/registry": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "put": { requestBody: Record<string, unknown>; response: unknown; query: Record<string, never> }
  }
  "/research/registry/history": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/registry/preview": {
    "post": { requestBody: Record<string, unknown>; response: unknown; query: Record<string, never> }
  }
  "/research/reports": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["ReportCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/reports/import": {
    "post": { requestBody: Components["Body_import_report_api_v1_research_reports_import_post"]; response: unknown; query: Record<string, never> }
  }
  "/research/reports/{report_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/reports/{report_id}/export.xlsx": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/reports/{report_id}/export.zip": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/reports/{report_id}/report.html": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/runs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["ResearchRunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/runs/{run_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/scan-jobs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["StrategyScanCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/scan-jobs/{job_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/scan-jobs/{job_id}/cancel": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/scan-jobs/{job_id}/retry": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/scans": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["StrategyScanCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/scans/{scan_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/screener-runs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["ScreenerRunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/screener-runs/{run_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/screener-runs/{run_id}/exports/{format}": {
    "post": { requestBody: Components["ExportSelection"]; response: unknown; query: Record<string, never> }
  }
  "/research/screener-runs/{run_id}/signals/{dataset_id}": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/sector-flow-runs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/sector-flow-runs/{run_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/signal-workspace/preview": {
    "post": { requestBody: Record<string, unknown>; response: unknown; query: Record<string, never> }
  }
  "/research/signal-workspace/reports": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "post": { requestBody: Record<string, unknown>; response: unknown; query: Record<string, never> }
  }
  "/research/signal-workspace/reports/{report_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/signal-workspace/reports/{report_id}/cross-validation.csv": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/signal-workspace/scan-jobs": {
    "post": { requestBody: Record<string, unknown>; response: unknown; query: Record<string, never> }
  }
  "/research/signal-workspace/scan-preview": {
    "post": { requestBody: Record<string, unknown>; response: unknown; query: Record<string, never> }
  }
  "/research/signal-workspace/source-preview": {
    "post": { requestBody: Record<string, unknown>; response: unknown; query: Record<string, never> }
  }
  "/research/signal-workspace/sources": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/stock-history": {
    "get": { requestBody: undefined; response: unknown; query: { "limit"?: number; "symbol": string } }
  }
  "/research/strategies": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/tdx-abnormal-jobs": {
    "post": { requestBody: Components["AbnormalUniverseRunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/tdx-b1-jobs": {
    "post": { requestBody: Components["B1UniverseRunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/tdx-ladder-jobs": {
    "post": { requestBody: Components["LadderUniverseRunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/tdx-sector-flow-jobs": {
    "post": { requestBody: Components["SectorFlowRunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/tdx-trend-jobs": {
    "post": { requestBody: Components["TrendUniverseRunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/tdx-universe-jobs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["TdxUniverseRunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/tdx-universe-jobs/{job_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/tdx-universe-jobs/{job_id}/cancel": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/trend-leader-runs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["TrendLeaderRunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/trend-leader-runs/{run_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/valuation-quote": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "dataset_id"?: (string | null); "symbol": string } }
  }
  "/research/valuation-runs": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["ValuationRunCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/valuation-runs/{run_id}": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/research/walk-forwards": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "post": { requestBody: Components["WalkForwardCreate"]; response: unknown; query: Record<string, never> }
  }
  "/research/walk-forwards/preview": {
    "post": { requestBody: Components["WalkForwardPreview"]; response: unknown; query: Record<string, never> }
  }
  "/research/walk-forwards/{job_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/walk-forwards/{job_id}/export.json": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/walk-forwards/{job_id}/tasks/{task_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/walk-forwards/{job_id}/{action}": {
    "post": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/watch-pool": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "put": { requestBody: Components["SaveRequest"]; response: unknown; query: Record<string, never> }
  }
  "/research/watch-pool/audit": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/research/watch-pool/import": {
    "post": { requestBody: Components["SaveRequest"]; response: unknown; query: Record<string, never> }
  }
  "/research/watch-pool/preview": {
    "post": { requestBody: Components["StateRequest"]; response: unknown; query: Record<string, never> }
  }
  "/session": {
    "get": { requestBody: undefined; response: Components["BrowserSessionResponse"]; query: Record<string, never> }
  }
  "/settings/groups/market_sources/import": {
    "post": { requestBody: Components["Import"]; response: unknown; query: Record<string, never> }
  }
  "/settings/groups/{group}": {
    "get": { requestBody: undefined; response: unknown; query: { "account_id"?: (string | null) } }
    "put": { requestBody: Components["trade_app__api__settings_routes__Save"]; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/settings/groups/{group}/audit": {
    "get": { requestBody: undefined; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/settings/groups/{group}/defaults-preview": {
    "post": { requestBody: Components["Revision"]; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/settings/groups/{group}/preview": {
    "post": { requestBody: Components["trade_app__api__settings_routes__Save"]; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/settings/groups/{group}/reset": {
    "post": { requestBody: Components["Reset"]; response: unknown; query: { "account_id"?: (string | null) } }
  }
  "/sim-accounts": {
    "post": { requestBody: Components["SimAccountCreate"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/activate-recovery": {
    "post": { requestBody: Components["SimRecoveryActivate"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/advance-market-day": {
    "post": { requestBody: Components["SimMarketAdvance"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/config": {
    "put": { requestBody: Components["SimConfigUpdate"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/drafts": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["SimDraftCreate"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/drafts/preview-batch": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "draft_id"?: Array<string> } }
  }
  "/sim-accounts/{account_id}/drafts/size": {
    "post": { requestBody: Components["SimDraftSizing"]; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/drafts/submit-batch": {
    "post": { requestBody: Components["SimDraftBatchSubmit"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/drafts/{draft_id}": {
    "put": { requestBody: Components["SimDraftUpdate"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/drafts/{draft_id}/cancel": {
    "post": { requestBody: undefined; response: unknown; query: { "expected_revision": number } }
  }
  "/sim-accounts/{account_id}/drafts/{draft_id}/preview": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/drafts/{draft_id}/submit": {
    "post": { requestBody: undefined; response: unknown; query: { "expected_config_version": number; "expected_revision": number; "expected_wallet_revision": number } }
  }
  "/sim-accounts/{account_id}/equity-reports": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "post": { requestBody: Record<string, unknown>; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/equity-reports/drafts": {
    "post": { requestBody: Record<string, unknown>; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/equity-reports/inputs": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/equity-reports/preview": {
    "post": { requestBody: Record<string, unknown>; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/equity-reports/size": {
    "post": { requestBody: Record<string, unknown>; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/equity-reports/{report_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "delete": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/equity-reports/{report_id}/export.pdf": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/fill-tags": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/fills": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/fills/{fill_id}/tags": {
    "put": { requestBody: Components["SimFillTagsSave"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/orders": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["SimOrderCreate"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/orders/{order_id}/cancel": {
    "post": { requestBody: undefined; response: unknown; query: { "expected_revision": number } }
  }
  "/sim-accounts/{account_id}/orders/{order_id}/fill": {
    "post": { requestBody: Components["SimFillCreate"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/orders/{order_id}/match-open": {
    "post": { requestBody: Components["SimOpenMatch"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/performance": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "date_basis"?: string; "date_from"?: (string | null); "date_to"?: (string | null) } }
  }
  "/sim-accounts/{account_id}/portfolio": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/reset": {
    "post": { requestBody: Components["SimReset"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/review-tags": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
    "post": { requestBody: Components["SimReviewTagCreate"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/review-tags/{tag_id}": {
    "delete": { requestBody: undefined; response: unknown; query: { "expected_revision": number } }
  }
  "/sim-accounts/{account_id}/settle": {
    "post": { requestBody: Components["SimSettle"]; response: unknown; query: Record<string, never> }
  }
  "/sim-accounts/{account_id}/tag-stats": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "date_from"?: (string | null); "date_to"?: (string | null) } }
  }
  "/sim-accounts/{account_id}/valuation": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "dataset_id"?: Array<string>; "decision_at": string; "strict"?: boolean } }
  }
  "/system/backups/preview": {
    "post": { requestBody: Components["Body_preview_backup_api_v1_system_backups_preview_post"]; response: unknown; query: Record<string, never> }
  }
  "/system/backups/restore-new": {
    "post": { requestBody: Components["Body_restore_backup_api_v1_system_backups_restore_new_post"]; response: unknown; query: Record<string, never> }
  }
  "/system/directory-picker": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
    "post": { requestBody: Components["DirectoryPick"]; response: unknown; query: Record<string, never> }
  }
  "/system/lifecycle": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/system/lifecycle/exit": {
    "post": { requestBody: Components["EmptyAction"]; response: unknown; query: Record<string, never> }
  }
  "/system/lifecycle/operations/{operation_id}": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/system/lifecycle/switch": {
    "post": { requestBody: Components["SwitchAction"]; response: unknown; query: Record<string, never> }
  }
  "/system/lifecycle/switch-preview": {
    "post": { requestBody: Components["SwitchPreview"]; response: unknown; query: Record<string, never> }
  }
  "/system/storage": {
    "get": { requestBody: undefined; response: unknown; query: Record<string, never> }
  }
  "/system/storage/copy": {
    "post": { requestBody: Components["CopyCommit"]; response: unknown; query: Record<string, never> }
  }
  "/system/storage/copy-preview": {
    "post": { requestBody: Components["CopyRequest"]; response: unknown; query: Record<string, never> }
  }
  "/tasks": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: { "account_id"?: (string | null) } }
  }
  "/health": {
    "get": { requestBody: undefined; response: Record<string, unknown>; query: Record<string, never> }
  }
}

export type ApiPath = keyof Operations
export type ApiRequestBody<P extends ApiPath, M extends keyof Operations[P]> = Operations[P][M] extends { requestBody: infer B } ? B : never
export type ApiResponse<P extends ApiPath, M extends keyof Operations[P]> = Operations[P][M] extends { response: infer R } ? R : never
