import { useEffect, useRef, useState } from 'react'
import { api } from './api'
import { PortfolioReportLibrary } from './portfolio-report-library'
import { useTaskDeepLink } from './task-deep-link'
import { Icon } from './workspace-icons'

type Axis = { key: string; values: string; min: string; max: string; precision: number }
type Spec = { type: string; title?: string; enum?: string[] }
type Source = { id: string; name: string; mode: string; state: string }
type Metrics = { total_return: number; max_drawdown: number; trade_count: number; win_rate: number | null; open_cycles: number }
type Selection = { selected_candidate_sha256: string | null; selected_task_id: string | null; reason: string | null; axis_values: Record<string, string> | null; training_evidence_sha256: string; ranking: Array<{ candidate_sha256: string; task_id: string; point_score: number; plateau_score: number | null; metrics: Metrics }>; rejected: Array<{ task_id: string; reason: string }> }
type Fold = { index: number; train_start: string; train_end: string; test_start: string; test_end: string; selection?: Selection | null; selection_sha256?: string | null }
type Task = { id: string; phase: string; fold_index: number; ordinal: number; axis_values: Record<string, string> | null; child_run_id: string | null; state: string; completed_days: number; total_days: number | null; chunk_count: number; error: string | null; reason: string | null; metrics: Metrics | null; portfolio?: { result: { trades: Record<string, unknown>[]; equity: Array<{ date: string; total_assets: string }>; quality_flags: string[] }; frozen_context: Record<string, unknown> } }
type Plan = { temporal: { folds: Fold[]; actual_folds: number; evaluation_points: number; unused_tail_bars: number; notes: string[] }; sampling: { actual_points: number; seed: number; samples: Array<Record<string, string>> } }
type Run = Partial<Plan> & { id: string; name: string; state: string; completed_tasks: number; total_tasks: number; active_fold: number; elapsed_ms: number; total_bytes: number; error: string | null; result_sha256: string | null; capabilities: Record<string, boolean>; folds?: Fold[]; tasks?: Task[]; result?: { oos_normalized_curve: Array<{ date: string; normalized_assets: number; fold_index: number }>; oos_compounded_return: number | null; oos_max_drawdown: number | null; completed_test_folds: number; planned_folds: number; oos_complete_cycles: number; limitations: string[]; quality_flags: string[] } | null }
type Preview = Plan & { requestKey: string; preview_sha256: string; source: Record<string, unknown>; frozen_child_input_bytes: number }
const endpoint = '/research/portfolio-walk-forwards'
const labels: Record<string, string> = { queued: '排队', pending: '尚未开始', running: '计算中', pausing: '等待当前5日检查点', paused: '已暂停', cancelling: '正在取消', cancelled: '已取消', succeeded: '已完成', failed: '失败', skipped: '训练无合格候选，跳过测试' }
const pct = (value: number | null | undefined) => value == null ? '—' : `${(value * 100).toFixed(2)}%`
function FoldTable({ folds }: { folds: Fold[] }) { return <div className="table-wrap"><table aria-label="组合滚动时间折"><thead><tr><th>折</th><th>扩展训练</th><th>后续独立测试</th></tr></thead><tbody>{folds.map(fold => <tr key={fold.index}><td>{fold.index + 1}</td><td>{fold.train_start} → {fold.train_end}</td><td>{fold.test_start} → {fold.test_end}</td></tr>)}</tbody></table></div> }

export function PortfolioWalkForwardWorkspace({ sourceRunId }: { sourceRunId?: string }) {
  const [sourceId, setSourceId] = useState(sourceRunId || ''), [sources, setSources] = useState<Source[]>([]), [schema, setSchema] = useState<Record<string, Spec>>({})
  const [name, setName] = useState('组合滚动验证'), [mode, setMode] = useState<'grid' | 'lhs'>('grid'), [seed, setSeed] = useState(20260926), [count, setCount] = useState(12), [limit, setLimit] = useState(60)
  const [axes, setAxes] = useState<Axis[]>([{ key: 'config.max_holding_bars', values: '2,5,10', min: '2', max: '20', precision: 0 }])
  const [time, setTime] = useState({ initial_train_bars: 60, test_bars: 20, gap_bars: 1, max_folds: 4, min_train_cycles: 1 })
  const [preview, setPreview] = useState<Preview | null>(null), [runs, setRuns] = useState<Run[]>([]), [selected, setSelected] = useState<Run | null>(null), [task, setTask] = useState<Task | null>(null)
  const [page, setPage] = useState(0), [deleteId, setDeleteId] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const live = useRef(true), selectedId = useRef(''), request = useRef(0)
  async function refresh() { const [history, source] = await Promise.all([api<Run[]>(endpoint), api<Source[]>('/research/portfolios')]); if (live.current) { setRuns(history); setSources(source.filter(row => row.state === 'succeeded')) } }
  useEffect(() => { live.current = true; refresh().catch(err => { if (live.current) setError(err.message) }); return () => { live.current = false } }, [])
  useEffect(() => { if (sourceRunId) { setSourceId(sourceRunId); refresh().catch(err => setError(err.message)) } }, [sourceRunId])
  useEffect(() => { let current = true; setSchema({}); setPreview(null); if (sourceId) api<{ schema: Record<string, Spec> }>(`/research/portfolio-experiments/schema/${sourceId}`).then(value => { if (current) setSchema(value.schema) }).catch(err => { if (current) setError(err.message) }); return () => { current = false } }, [sourceId])
  const active = runs.some(run => ['queued', 'running', 'pausing', 'cancelling'].includes(run.state))
  useEffect(() => { if (!active) return; let pending = false; const timer = setInterval(async () => { if (pending) return; pending = true; try { await refresh(); const id = selectedId.current; if (id) { const value = await api<Run>(`${endpoint}/${id}`); if (live.current && id === selectedId.current) setSelected(value) } } catch (err) { if (live.current) setError(err instanceof Error ? err.message : String(err)) } finally { pending = false } }, 1800); return () => clearInterval(timer) }, [active])
  async function perform(action: () => Promise<void>) { if (busy) return; setBusy(true); setError(''); try { await action() } catch (err) { if (live.current) setError(err instanceof Error ? err.message : String(err)) } finally { if (live.current) setBusy(false) } }
  async function choose(id: string) { selectedId.current = id; const value = await api<Run>(`${endpoint}/${id}`); if (live.current && id === selectedId.current) { setSelected(value); setTask(null); setPage(0) } }
  useTaskDeepLink('portfolio_walk_forward', choose, '[aria-label="组合滚动验证详情"]', setError)
  function chooseTask(id: string) { perform(async () => { const parent = selectedId.current, token = ++request.current; const value = await api<Task>(`${endpoint}/${parent}/tasks/${id}`); if (live.current && token === request.current && parent === selectedId.current) setTask(value) }) }
  const body = () => { const values: Record<string, unknown> = {}; for (const axis of axes) { if (values[axis.key]) throw new Error('候选维度不可重复。'); values[axis.key] = mode === 'grid' ? { values: axis.values.split(',').map(value => value.trim()).filter(Boolean) } : { min: axis.min, max: axis.max, precision: axis.precision } } return { base_run_id: sourceId, sampling_mode: mode, axes: values, seed, sample_points: count, max_points: limit, ...time } }
  const requestKey = JSON.stringify({ sourceId, mode, axes, seed, count, limit, time })
  const changeAxis = (at: number, value: Partial<Axis>) => setAxes(current => current.map((axis, index) => at === index ? { ...axis, ...value } : axis))
  const curve = selected?.result?.oos_normalized_curve || [], values = curve.map(point => point.normalized_assets), low = Math.min(...values), high = Math.max(...values)
  const curvePath = values.map((value, index) => `${index ? 'L' : 'M'} ${20 + 720 * index / Math.max(1, values.length - 1)} ${155 - 130 * (value - low) / Math.max(.0001, high - low)}`).join(' ')
  return <section className="card" aria-label="组合滚动验证" style={{ marginTop: 24 }}><h3>组合 Walk-forward · 训练后独立测试</h3><p className="muted">扩展训练段完成所有冻结候选后选参，再执行间隔后的测试段。训练进程仅接收训练末日及以前的日线。候选范围先冻结，禁止使用本折测试绩效重选本折参数。各阶段只做同一组合引擎的5日期分块计算。</p><p className="muted">固定样本的历史市场成分未经核验。各测试折重置资金与持仓，按收益比例拼接；不代表跨折连续持仓。测试末日保留持仓估值，未清仓不伪造卖出。人工选择候选是否事先看过测试段，系统无法证明。</p>
    {error && <p role="alert" className="alert error">{error}</p>}<div className="form-grid"><label><span>组合WF来源</span><select value={sourceId} onChange={event => setSourceId(event.target.value)}><option value="">选择已完成组合</option>{sources.map(source => <option key={source.id} value={source.id}>{source.name} · {source.mode} · {source.id.slice(0, 8)}</option>)}</select></label><label><span>组合WF名称</span><input value={name} maxLength={80} onChange={event => setName(event.target.value)} /></label><label><span>组合WF采样</span><select value={mode} onChange={event => setMode(event.target.value as 'grid' | 'lhs')}><option value="grid">完整网格</option><option value="lhs">LHS</option></select></label><label><span>组合WF种子</span><input type="number" min={0} max={2147483647} value={seed} onChange={event => setSeed(Number(event.target.value))} /></label><label><span>每折候选上限</span><input type="number" min={1} max={400} value={limit} onChange={event => setLimit(Number(event.target.value))} /></label>{mode === 'lhs' && <label><span>组合WF采样点数</span><input type="number" min={1} max={400} value={count} onChange={event => setCount(Number(event.target.value))} /></label>}
      {([['initial_train_bars', '组合首次训练日期数', 32, 1800], ['test_bars', '组合每折测试日期数', 10, 1000], ['gap_bars', '组合训练测试间隔', 0, 60], ['max_folds', '组合最多折数', 1, 12], ['min_train_cycles', '训练最少完整持仓周期', 0, 1000]] as const).map(([key, title, min, max]) => <label key={key}><span>{title}</span><input type="number" min={min} max={max} value={time[key]} onChange={event => setTime({ ...time, [key]: Number(event.target.value) })} /></label>)}</div>
    {axes.map((axis, index) => <fieldset key={index} style={{ marginTop: 12 }}><legend>WF候选维度 {index + 1}</legend><div className="form-grid"><label><span>组合WF参数 {index + 1}</span><select value={axis.key} onChange={event => changeAxis(index, { key: event.target.value })}>{Object.entries(schema).filter(([, spec]) => mode === 'grid' || ['integer', 'number'].includes(spec.type)).map(([key, spec]) => <option key={key} value={key}>{spec.title || key} · {key}</option>)}</select></label>{mode === 'grid' ? <label><span>组合WF取值 {index + 1}</span><input value={axis.values} onChange={event => changeAxis(index, { values: event.target.value })} placeholder="逗号分隔" /></label> : <><label><span>组合WF下限 {index + 1}</span><input value={axis.min} onChange={event => changeAxis(index, { min: event.target.value })} /></label><label><span>组合WF上限 {index + 1}</span><input value={axis.max} onChange={event => changeAxis(index, { max: event.target.value })} /></label><label><span>组合WF精度 {index + 1}</span><input type="number" min={0} max={6} value={axis.precision} onChange={event => changeAxis(index, { precision: Number(event.target.value) })} /></label></>}<button className="button secondary" disabled={axes.length === 1} onClick={() => setAxes(current => current.filter((_, at) => at !== index))}>移除WF维度 {index + 1}</button></div></fieldset>)}
    <div className="toolbar" style={{ marginTop: 16 }}><button className="button secondary" disabled={axes.length >= 8} onClick={() => setAxes([...axes, { key: 'config.position_pct', values: '.2,.4', min: '.1', max: '.5', precision: 3 }])}>增加WF维度</button><button className="button" disabled={busy || !sourceId || !Object.keys(schema).length} onClick={() => perform(async () => { const value = await api<Omit<Preview, 'requestKey'>>(`${endpoint}/preview`, 'POST', body()); if (live.current) setPreview({ ...value, requestKey }) })}>预览组合滚动计划</button><button className="button secondary" disabled={busy} onClick={() => perform(refresh)}><Icon name="refresh" />刷新组合WF</button></div>
    {preview?.requestKey === requestKey && <section className="alert" aria-label="组合WF冻结计划"><p>{preview.temporal.actual_folds} 折 · 每折 {preview.sampling.actual_points} 个训练候选 · 最多 {preview.temporal.evaluation_points} 个阶段任务 · 不使用尾部 {preview.temporal.unused_tail_bars} 个日期</p><p>{preview.temporal.notes.join('；')}</p><FoldTable folds={preview.temporal.folds} /><details><summary>冻结候选与来源</summary><pre style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify({ candidates: preview.sampling, source: preview.source, input_bytes: preview.frozen_child_input_bytes, sha256: preview.preview_sha256 }, null, 2)}</pre></details><button className="button" disabled={busy || !name.trim()} onClick={() => perform(async () => { const value = await api<Run>(endpoint, 'POST', { ...body(), name: name.trim(), expected_preview_sha256: preview.preview_sha256 }); await refresh(); await choose(value.id); setPreview(null) })}>确认创建组合滚动验证</button></section>}
    <div className="table-wrap"><table aria-label="组合WF历史"><thead><tr><th>名称</th><th>状态 / 阶段</th><th>消耗</th><th>操作</th></tr></thead><tbody>{runs.map(run => <tr key={run.id}><td>{run.name}</td><td>{labels[run.state]} · {run.completed_tasks}/{run.total_tasks}</td><td>{(run.elapsed_ms / 1000).toFixed(1)}秒 · {(run.total_bytes / 1048576).toFixed(2)}MiB</td><td><button className="button secondary" disabled={busy} onClick={() => perform(() => choose(run.id))}>查看组合WF</button>{run.capabilities.delete && <button className="button secondary" onClick={() => setDeleteId(run.id)}><Icon name="delete" />删除组合WF</button>}</td></tr>)}</tbody></table></div>
    {deleteId && <div className="alert"><p>删除组合滚动验证的列表记录？训练选择、阶段证据及独立报告保留。</p><button className="button danger" disabled={busy} onClick={() => perform(async () => { await api(`${endpoint}/${deleteId}`, 'DELETE', {}); if (selectedId.current === deleteId) { selectedId.current = ''; setSelected(null); setTask(null) } setDeleteId(''); await refresh() })}><Icon name="check" />确认删除组合WF</button><button className="button secondary" onClick={() => setDeleteId('')}>保留组合WF</button></div>}
    {selected && <section aria-label="组合滚动验证详情"><h4>{selected.name} · {labels[selected.state]}</h4><p>完成 {selected.completed_tasks}/{selected.total_tasks} 个训练或测试阶段 · 当前折 {selected.active_fold + 1}。{selected.error}</p><div className="toolbar">{[['pause', '暂停组合WF'], ['resume', '续跑组合WF'], ['cancel', '取消组合WF'], ['retry', '重试组合WF']].filter(([action]) => selected.capabilities[action]).map(([action, title]) => <button key={action} className="button secondary" disabled={busy} onClick={() => perform(async () => { await api(`${endpoint}/${selected.id}/${action}`, 'POST', {}); await refresh(); await choose(selected.id) })}>{title}</button>)}<a className="button secondary" href={`/api/v1${endpoint}/${selected.id}/export.json`} download>导出组合WF分析</a></div><FoldTable folds={selected.folds || []} />
      {selected.result && <section aria-label="组合样本外结果"><h5>测试折归一化拼接结果</h5><p>完成测试 {selected.result.completed_test_folds}/{selected.result.planned_folds} 折 · 拼接收益 {pct(selected.result.oos_compounded_return)} · 拼接回撤 {pct(selected.result.oos_max_drawdown)} · 完整持仓周期 {selected.result.oos_complete_cycles}</p>{curve.length > 0 && <svg role="img" aria-label="组合样本外归一化曲线" viewBox="0 0 760 175" style={{ width: '100%', maxHeight: 250 }}><path d={curvePath} fill="none" stroke="var(--chart-series1)" strokeWidth="2.5" /></svg>}<p className="muted">{selected.result.limitations.join('；')}</p><p className="muted">{selected.result.quality_flags.join(' · ')}</p></section>}
      {selected.folds?.map(fold => <details key={fold.index}><summary>折 {fold.index + 1} · {fold.selection ? '训练选择已冻结' : '等待训练全部完成'}</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify({ selection_sha256: fold.selection_sha256, selection: fold.selection }, null, 2)}</pre></details>)}
      <div className="table-wrap"><table aria-label="组合WF阶段"><thead><tr><th>折 / 阶段</th><th>参数</th><th>状态 / 检查点</th><th>收益 / 回撤 / 周期</th><th>操作</th></tr></thead><tbody>{selected.tasks?.slice(page * 50, page * 50 + 50).map(item => <tr key={item.id}><td>{item.fold_index + 1} / {item.phase === 'train' ? '训练' : '后续测试'}</td><td>{JSON.stringify(item.axis_values)}</td><td>{labels[item.state]} · {item.completed_days}/{item.total_days ?? '—'} · {item.chunk_count} 检查点<br />{item.error || item.reason}</td><td>{pct(item.metrics?.total_return)} / {pct(item.metrics?.max_drawdown)} / {item.metrics?.trade_count ?? '—'}</td><td><button className="button secondary" disabled={busy || !item.child_run_id} onClick={() => chooseTask(item.id)}>查看阶段组合</button></td></tr>)}</tbody></table></div><div className="toolbar"><button className="button secondary" disabled={page === 0} onClick={() => setPage(page - 1)}>阶段上一页</button><span>{page + 1}/{Math.max(1, Math.ceil((selected.tasks?.length || 0) / 50))}</span><button className="button secondary" disabled={(page + 1) * 50 >= (selected.tasks?.length || 0)} onClick={() => setPage(page + 1)}>阶段下一页</button></div>
      {task?.portfolio && <section aria-label="组合WF阶段详情"><h5>折 {task.fold_index + 1} · {task.phase === 'train' ? '训练候选' : '独立测试'} · {labels[task.state]}</h5><p>成交 {task.portfolio.result.trades.length} 笔 · 权益 {task.portfolio.result.equity.length} 个日期</p><details><summary>阶段冻结输入与完整成交</summary><pre style={{ whiteSpace: 'pre-wrap', maxHeight: 500, overflow: 'auto' }}>{JSON.stringify({ input: task.portfolio.frozen_context, trades: task.portfolio.result.trades }, null, 2)}</pre></details><a className="button secondary" href={`/api/v1/research/portfolios/${task.child_run_id}/export.json`} download>下载阶段全部组合证据</a><PortfolioReportLibrary sourceRunId={task.state === 'succeeded' ? task.child_run_id || undefined : undefined} /></section>}
    </section>}
  </section>
}
