import { useEffect, useMemo, useRef, useState } from 'react'
import { api } from './api'
import { navigateResearch, type ResearchNavigation } from './research-navigation'
import { ResearchTradeDownloads } from './research-table-downloads'
import { StrategyPresets } from './strategy-presets'
import { AIContextButton } from './ai-launcher'
import { useTaskDeepLink } from './task-deep-link'
import type { Strategy } from './research'
import type { EventProfileCatalog } from './event-profiles'

type Dataset = { id: string; symbol: string; first_date: string; last_date: string; bar_count: number; availability_quality: string }
type Config = { initial_capital: string; position_pct: string; max_positions: number; max_holding_bars: number; top_n: number; entry_top_k: number; entry_delay_bars: number; execution_strict: boolean; pool_roll: string; stop_loss_pct: string; take_profit_pct: string; trailing_stop_pct: string; intraday_trailing: boolean; trailing_reduce_ratio: string; daily_weak_clear: boolean; weak_confirm_days: number; invalidate_pending: boolean; ambiguity_policy: string; fee_config: Record<string, string>; trail_activate: string; time_stop_days: number; time_stop_min_gain: string; breakeven_trigger: string }
type Trade = { date: string; symbol: string; side: string; quantity: number; price: string; reference_price: string; fees: string; realized_pnl: string | null; reason: string; phase: string; decision_at?: string | null; known_at?: string | null; signal_date?: string; reason_metrics: Record<string, unknown> }
type Equity = { date: string; total_assets: string; cash: string; position_count: number; positions: Record<string, { quantity: number; mark: string }> }
type Pool = { date: string; source_date: string; decision_at: string; members: string[]; trigger: string; rows: Array<{ symbol: string; in_pool: boolean; score: number | null; known_at: string | null; reason: string; components: Record<string, unknown> }> }
type Summary = { total_return: string; max_drawdown: string; initial_capital: string; ending_assets: string; buy_count: number; sell_count: number; realized_pnl: string; total_fees: string; open_positions: Record<string, { quantity: number; cost: string; entry_date: string }>; quality_flags: string[] }
type Run = { id: string; name: string; mode: string; state: string; error: string | null; completed_days: number; total_days: number; symbol_count: number; chunk_count: number; elapsed_ms: number; summary: Summary; result_sha256: string | null; checkpoint_sha256: string; capabilities: Record<string, boolean>; frozen_context?: Record<string, unknown>; limitations?: string[]; result?: Summary & { trades: Trade[]; equity: Equity[]; pool_history: Pool[]; decisions: Array<{ date: string; symbol: string; status: string; reason: string }> } }
type Preview = { key: string; preview_sha256: string; frozen_context: Record<string, unknown>; limitations: string[] }
const states: Record<string, string> = { queued: '排队', running: '计算中', pausing: '正在完成当前检查点', paused: '已暂停', cancelling: '正在取消', cancelled: '已取消', succeeded: '已完成', failed: '失败' }
const modeNames: Record<string, string> = { matrix_raw_s1_s9: '原始矩阵 S1–S9', traditional_runtime14: '传统策略运行器', aligned_wyckoff_events: '维科夫事件矩阵' }
const reasons: Record<string, string> = { CLASSIC_SIGNAL_NEXT_OPEN: '经典策略退出（下一开盘）', PRIOR_KNOWN_SIGNAL_NEXT_OPEN: '历史已知信号开盘买入', MATRIX_S8_S9_NEXT_OPEN: '矩阵 S8/S9 开盘退出', ALIGNED_EVENTS_NEXT_OPEN: '事件矩阵退出事件开盘卖出', RISK_EVENT_NEXT_OPEN: '风险事件开盘退出', MAX_HOLDING_NEXT_OPEN: '持有期届满开盘退出', OPEN_GAP_STOP_LOSS: '开盘跳空止损', OPEN_GAP_TAKE_PROFIT: '开盘跳空止盈', DAILY_STOP_LOSS: '日线预设止损', DAILY_TAKE_PROFIT: '日线预设止盈', OBSERVED_TRAILING_NEXT_OPEN: '已观察回撤次日减仓', KNOWN_CLOSE_WEAK_NEXT_OPEN: '收盘走弱确认清仓', MAX_POSITIONS: '持仓数量上限', INSUFFICIENT_CASH: '可用现金不足', DAILY_TOP_K: '当日候选数量限制', POOL_OR_RISK_INVALIDATION: '候选池或风险失效' }
Object.assign(reasons, { BAND_TIME_STOP_NEXT_OPEN: '已知时间止损，次日开盘', BAND_MA10_TRAIL_NEXT_OPEN: '已知峰值激活MA10退出，次日开盘', BAND_MA20_BOX_BREAK_NEXT_OPEN: '已知MA20及箱体破位，次日开盘', OPEN_GAP_BREAKEVEN_STOP: '保本障碍开盘跳空', DAILY_BREAKEVEN_STOP: '此前激活的保本障碍', OPEN_GAP_BOX_STRUCTURE_STOP: '箱体结构止损开盘跳空', DAILY_BOX_STRUCTURE_STOP: '入场冻结箱顶结构止损' })
const pct = (value: string | undefined) => value == null ? '—' : `${(Number(value) * 100).toFixed(2)}%`

function PoolComponents({ value }: { value: Record<string, unknown> }) {
  const flags = Object.entries(value).filter(([key]) => /^S[1-9]$/.test(key))
  const evidence = Object.fromEntries(Object.entries(value).filter(([key]) => !/^S[1-9]$/.test(key)))
  return <>{flags.map(([key, hit]) => `${key}: ${hit ? '✓' : '−'}`).join(' · ')}{Object.keys(evidence).length > 0 && <details><summary>事件门槛、评分与确认依据</summary><pre style={{ whiteSpace: 'pre-wrap', maxHeight: 280, overflow: 'auto' }}>{JSON.stringify(evidence, null, 2)}</pre></details>}</>
}

export function PortfolioWorkspace({ accountId, onNavigate }: { accountId?: string; onNavigate?: (next: ResearchNavigation) => void }) {
  const [panel, setPanel] = useState<'configure' | 'history' | 'result'>('configure')
  const [step, setStep] = useState(0)
  const steps = ['样本与日期', '信号策略', '资金与执行', '退出与费用', '预览提交']
  const [datasets, setDatasets] = useState<Dataset[]>([])
  const [strategies, setStrategies] = useState<Strategy[]>([])
  const [profiles, setProfiles] = useState<EventProfileCatalog | null>(null)
  const [profileId, setProfileId] = useState('')
  const [datasetIds, setDatasetIds] = useState<string[]>([])
  const [filter, setFilter] = useState('')
  const [mode, setMode] = useState('matrix_raw_s1_s9')
  const [strategyId, setStrategyId] = useState('')
  const [params, setParams] = useState<Record<string, string>>({})
  const [eventParams, setEventParams] = useState<Record<string, unknown>>({})
  const [eventSchema, setEventSchema] = useState<Record<string, { type: string; options?: string[]; minimum?: number; maximum?: number }>>({})
  const [config, setConfig] = useState<Config | null>(null)
  const [name, setName] = useState('固定样本组合实验')
  const [start, setStart] = useState('')
  const [end, setEnd] = useState('')
  const [jobs, setJobs] = useState<Run[]>([])
  const [selected, setSelected] = useState<Run | null>(null)
  const [detail, setDetail] = useState<Run | null>(null)
  const [preview, setPreview] = useState<Preview | null>(null)
  const [poolDate, setPoolDate] = useState('')
  const [tradePage, setTradePage] = useState(0)
  const [deleteId, setDeleteId] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const alive = useRef(true), selectedId = useRef('')
  useEffect(() => { alive.current = true; return () => { alive.current = false } }, [])
  async function refresh() { const values = await api<Run[]>('/research/portfolios'); if (alive.current) setJobs(values) }
  useEffect(() => { Promise.all([api<Dataset[]>('/market/datasets'), api<Strategy[]>('/research/strategies'), api<EventProfileCatalog>('/research/event-profiles'), api<{ defaults: Config; event_defaults: Record<string, unknown>; event_schema: typeof eventSchema }>('/research/portfolios/schema')]).then(([ds, ss, pp, cc]) => { if (!alive.current) return; setDatasets(ds); setStrategies(ss); setProfiles(pp); setProfileId(pp.active_profile_id); setConfig(cc.defaults); setEventParams(cc.event_defaults); setEventSchema(cc.event_schema); const initial = ss.find(s => s.default_in_rebuild && s.enabled_in_rebuild !== false && s.signal_params !== null); setStrategyId(initial?.id || ''); setParams(initial?.signal_params || {}) }).catch(err => { if (alive.current) setError(err.message) }); refresh().catch(err => { if (alive.current) setError(err.message) }) }, [])
  const active = jobs.some(job => ['queued', 'running', 'pausing', 'cancelling'].includes(job.state))
  useEffect(() => { if (!active) return; let pending = false; const timer = setInterval(async () => { if (pending) return; pending = true; try { await refresh(); const id = selectedId.current; if (id) { const value = await api<Run>(`/research/portfolios/${id}`); if (alive.current && id === selectedId.current) setSelected(value) } } catch (err) { if (alive.current) setError(err instanceof Error ? err.message : String(err)) } finally { pending = false } }, 1800); return () => clearInterval(timer) }, [active])
  const usesProfile = mode === 'aligned_wyckoff_events' || mode === 'traditional_runtime14' && ['wyckoff_trend_v1', 'wyckoff_trend_v2', 'score_only_rank_v1'].includes(strategyId)
  const body = useMemo(() => ({ dataset_ids: [...datasetIds].sort(), mode, strategy_id: mode === 'traditional_runtime14' ? strategyId : null,
    params: mode === 'traditional_runtime14' ? params : mode === 'aligned_wyckoff_events' ? eventParams : {}, config, start_date: start || null, end_date: end || null,
    ...(usesProfile ? { event_profile_id: profileId, event_profile_revision: profiles?.profiles.find(item => item.profile_id === profileId)?.revision } : {}) }), [datasetIds, mode, strategyId, params, eventParams, config, start, end, usesProfile, profileId, profiles])
  const key = JSON.stringify(body), checked = preview?.key === key ? preview : null
  async function perform(action: () => Promise<void>) { setBusy(true); setError(''); try { await action() } catch (err) { if (alive.current) setError(err instanceof Error ? err.message : String(err)) } finally { if (alive.current) setBusy(false) } }
  async function choose(id: string) { setPanel('result'); selectedId.current = id; setDetail(null); setDeleteId(''); const value = await api<Run>(`/research/portfolios/${id}`); if (alive.current && selectedId.current === id) setSelected(value) }
  useTaskDeepLink('portfolio', choose, '[aria-label="组合结果"]', setError)
  async function loadResult() { const id = selectedId.current; const value = await api<Run>(`/research/portfolios/${id}/result`); if (alive.current && selectedId.current === id) { setDetail(value); setPoolDate(value.result?.pool_history[0]?.date || ''); setTradePage(0) } }
  async function control(id: string, action: string) { await api(`/research/portfolios/${id}${action === 'delete' ? '' : '/' + action}`, action === 'delete' ? 'DELETE' : 'POST', {}); if (action === 'delete') { selectedId.current = ''; setSelected(null); setDetail(null); setDeleteId(''); setPanel('history') } else await choose(id); await refresh() }
  const strategy = strategies.find(item => item.id === strategyId)
  const curve = detail?.result?.equity || []
  const values = curve.map(point => Number(point.total_assets)), low = Math.min(...values), high = Math.max(...values)
  const chart = curve.map((point, index) => `${index ? 'L' : 'M'} ${index / Math.max(1, curve.length - 1) * 760} ${155 - (Number(point.total_assets) - low) / Math.max(1, high - low) * 145}`).join(' ')
  const pool = detail?.result?.pool_history.find(item => item.date === poolDate)
  const trades = detail?.result?.trades || []
  return <section className="card" aria-label="固定样本组合回测">
    <div className="section-header"><div><h3>固定样本组合回测</h3><p className="muted">三种信号路径共享资金与持仓规则。先配置样本，再预览并创建；任务在后台按检查点运行。</p></div><button className="button secondary" disabled={busy} onClick={() => perform(refresh)}>刷新组合历史</button></div>
    <div className="research-panel-tabs" role="tablist" aria-label="组合回测工作区">{([['configure', '配置组合'], ['history', '任务历史'], ['result', '运行结果']] as const).map(([value, label]) => <button key={value} role="tab" id={`portfolio-tab-${value}`} aria-controls={`portfolio-panel-${value}`} aria-selected={panel === value} onClick={() => setPanel(value)}>{label}{value === 'history' ? ` · ${jobs.length}` : ''}</button>)}</div>
    {error && <p className="alert error" role="alert">{error}</p>}
    <div className="research-pane" role="tabpanel" id="portfolio-panel-configure" aria-labelledby="portfolio-tab-configure" hidden={panel !== 'configure'}>
      <nav className="research-steps" aria-label="组合配置步骤">{steps.map((label, index) => <button key={label} aria-current={step === index ? 'step' : undefined} onClick={() => setStep(index)}><span className="research-step-number">{index + 1}</span>{label}</button>)}</nav>
      <div className="research-step-panel" hidden={step !== 0}><h4>选择研究样本与日期</h4><p className="muted">这是手工选定的固定研究样本，不能视作历史全市场成分。空日期由预览根据所选行情自动确定。</p><div className="form-grid">
<label><span>组合实验名称</span><input value={name} maxLength={80} onChange={event => setName(event.target.value)} /></label>      <label><span>组合开始日期</span><input type="date" value={start} onChange={event => setStart(event.target.value)} /></label><label><span>组合结束日期</span><input type="date" value={end} onChange={event => setEnd(event.target.value)} /></label>
</div>
    <section><h4>固定研究样本 · 已选 {datasetIds.length} / 64 个证券</h4><p className="muted">同一证券只选一份冻结行情；前后缀别名也会检查重复。组合日历合计最多 2000 日期，总行情最多 60000 根；空日期按预览自动选择。</p><label><span>筛选组合行情</span><input value={filter} onChange={event => setFilter(event.target.value)} placeholder="证券代码或数据集编号" /></label><div className="table-wrap" style={{ maxHeight: 260, overflowY: 'auto' }}><table aria-label="组合研究样本"><thead><tr><th>选择</th><th>证券</th><th>冻结日期</th><th>行数</th><th>可得性</th></tr></thead><tbody>{datasets.filter(item => !filter || `${item.symbol} ${item.id}`.toLowerCase().includes(filter.toLowerCase())).map(item => <tr key={item.id}><td><input type="checkbox" aria-label={`组合样本 ${item.symbol} ${item.id.slice(0, 8)}`} checked={datasetIds.includes(item.id)} disabled={!datasetIds.includes(item.id) && datasetIds.length >= 64} onChange={event => setDatasetIds(ids => event.target.checked ? [...ids, item.id] : ids.filter(id => id !== item.id))} /></td><td>{item.symbol}<br /><small>{item.id.slice(0, 8)}</small></td><td>{item.first_date} → {item.last_date}</td><td>{item.bar_count}</td><td>{item.availability_quality === 'provided_availability' ? '提供了可得时间' : '历史可得时间未知'}</td></tr>)}</tbody></table></div></section>
</div>
      <div className="research-step-panel" hidden={step !== 1}><h4>选择信号路径</h4><div className="form-grid">
      <label><span>组合信号路径</span><select value={mode} onChange={event => setMode(event.target.value)}><option value="matrix_raw_s1_s9">原始矩阵 S1–S9</option><option value="traditional_runtime14">传统策略运行器</option><option value="aligned_wyckoff_events">维科夫事件矩阵 · 独立事件语义</option></select></label>
      {mode === 'traditional_runtime14' && <label><span>组合传统策略</span><select value={strategyId} onChange={event => { setStrategyId(event.target.value); setParams(strategies.find(item => item.id === event.target.value)?.signal_params || {}) }}><option value="">请选择已启用单股策略</option>{strategies.filter(item => item.signal_params && item.enabled_in_rebuild !== false).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
      {usesProfile && <label><span>组合冻结事件模板</span><select value={profileId} onChange={event => setProfileId(event.target.value)}>{profiles?.profiles.map(item => <option key={item.profile_id} value={item.profile_id}>{item.name} · 修订 {item.revision}</option>)}</select></label>}
</div>{mode === 'matrix_raw_s1_s9' && <p className="muted">原始价量公式决定 S1–S9；相对强度前 N 项与股票池刷新在下一步配置。它与单日冻结池插件、维科夫事件矩阵采用不同信号口径。</p>}
    {mode === 'traditional_runtime14' && <section><h4>传统策略参数与预设</h4><div className="form-grid">{Object.entries(params).map(([field, value]) => <label key={field}><span>{strategy?.params_schema[field]?.title || field}</span><input value={value} onChange={event => setParams({ ...params, [field]: event.target.value })} /></label>)}</div><StrategyPresets strategyId={strategyId} params={params} onApply={setParams} accountId={accountId} /></section>}
    {mode === 'aligned_wyckoff_events' && <section aria-label="事件矩阵参数" style={{ marginTop: 16 }}><h4>独立事件矩阵门槛</h4><p className="muted">仅事件发生日等于当前观察日时触发；确认状态只使用当时已知前缀，不把后续确认回写到过去。默认延续旧组合回测的最低入场质量55分。S5/S7表示事件买入、S8表示事件退出，其余S项不用作原始价量公式；同时出现退出与入场时退出优先。</p>
      <div className="form-grid">{([['window_days', '事件观察窗口'], ['min_score', '事件入场质量下限'], ['min_event_count', '最少事件数量'], ['health_score_min', '事件健康分下限'], ['event_score_min', '事件分下限']] as const).map(([field, label]) => <label key={field}><span>{label}</span><input type="number" min={eventSchema[field]?.minimum} max={eventSchema[field]?.maximum} value={String(eventParams[field] ?? '')} onChange={event => setEventParams({ ...eventParams, [field]: event.target.value })} /></label>)}
        <label><span>事件等级下限</span><select value={String(eventParams.event_grade_min || 'C')} onChange={event => setEventParams({ ...eventParams, event_grade_min: event.target.value })}>{['C', 'B', 'A'].map(value => <option key={value}>{value}</option>)}</select></label>
        <label><span>事件确认口径</span><select value={String(eventParams.confirmation_policy || 'event')} onChange={event => setEventParams({ ...eventParams, confirmation_policy: event.target.value })}><option value="event">逐事件确认，推荐</option><option value="legacy_snapshot">旧版全快照确认，对照用</option></select></label>
        <label><input type="checkbox" checked={eventParams.require_sequence === true} onChange={event => setEventParams({ ...eventParams, require_sequence: event.target.checked })} />事件必须满足序列</label><label><input type="checkbox" checked={eventParams.require_key_event_confirmation === true} onChange={event => setEventParams({ ...eventParams, require_key_event_confirmation: event.target.checked })} />事件入场必须已确认</label>
      </div><p className="muted">逐事件确认防止借用另一事件的确认状态。旧版对照口径使用快照总体状态，两种口径可能产生不同交易。样本内股票池保留可计算证券，事件入场门槛单独记录，因此延迟入场不要求次日重复产生同一事件。风险事件不能作为做多入场选项。</p>
      {(['entry_events', 'exit_events'] as const).map(field => <fieldset key={field}><legend>{field === 'entry_events' ? '事件矩阵入场事件' : '事件矩阵退出事件'}</legend><div className="toolbar" style={{ flexWrap: 'wrap' }}>{eventSchema[field]?.options?.map(event => { const values = Array.isArray(eventParams[field]) ? eventParams[field] as string[] : []; return <label key={event}><input type="checkbox" aria-label={`${field === 'entry_events' ? '入场' : '退出'}事件 ${event}`} checked={values.includes(event)} onChange={change => setEventParams({ ...eventParams, [field]: change.target.checked ? [...values, event] : values.filter(value => value !== event) })} />{event}</label> })}</div></fieldset>)}
    </section>}
</div>
    {config && (step === 2 || step === 3) && <section className="research-step-panel"><h4>{step === 2 ? '资金分配与执行时点' : '退出规则与费用'}</h4><div className="form-grid">
      {([['initial_capital', '组合初始资金'], ['position_pct', '单证券资产占比 0–1'], ['stop_loss_pct', '预设止损比例 0–0.5'], ['take_profit_pct', '预设止盈比例 0–1.5'], ['trailing_stop_pct', '已观察回撤阈值 0–0.5'], ['trailing_reduce_ratio', '回撤减仓比例 0–1']] as const).filter(([field]) => step === 2 ? ['initial_capital', 'position_pct'].includes(field) : !['initial_capital', 'position_pct'].includes(field)).map(([field, label]) => <label key={field}><span>{label}</span><input value={config[field]} onChange={event => setConfig({ ...config, [field]: event.target.value })} /></label>)}
      {([['max_positions', '最多持有证券数'], ['max_holding_bars', '最长持有日线数'], ['entry_top_k', '每日买入候选前K项，0不限'], ['entry_delay_bars', '买入延迟日线数 1–5'], ['weak_confirm_days', '走弱确认日数'], ...(mode === 'matrix_raw_s1_s9' ? [['top_n', '矩阵 S3 相对强度前N项']] as const : [])] as Array<[keyof Config, string]>).filter(([field]) => step === 2 ? !['max_holding_bars', 'weak_confirm_days'].includes(field) : ['max_holding_bars', 'weak_confirm_days'].includes(field)).map(([field, label]) => <label key={field}><span>{label}</span><input type="number" min={0} value={Number(config[field])} onChange={event => setConfig({ ...config, [field]: Number(event.target.value) })} /></label>)}
      {step === 2 && <label><span>样本内股票池刷新</span><select value={config.pool_roll} onChange={event => setConfig({ ...config, pool_roll: event.target.value })}><option value="static">首个交易日固定</option><option value="daily">每日</option><option value="weekly">每个新日历周</option><option value="position">实际卖出后下个样本日期</option></select></label>}
      {step === 3 && <label><span>日线双触发假设</span><select value={config.ambiguity_policy} onChange={event => setConfig({ ...config, ambiguity_policy: event.target.value })}><option value="conservative">保守：止损优先</option><option value="optimistic">乐观敏感性：止盈优先</option></select></label>}
      {([['execution_strict', '时点严格：拒绝未知/不完整历史'], ['intraday_trailing', '启用已观察回撤后开盘减仓'], ['daily_weak_clear', '启用收盘走弱确认后开盘清仓'], ['invalidate_pending', '风险事件使待买意图失效']] as const).filter(([field]) => step === 2 ? ['execution_strict', 'invalidate_pending'].includes(field) : !['execution_strict', 'invalidate_pending'].includes(field)).map(([field, label]) => <label key={field}><input type="checkbox" checked={config[field]} onChange={event => setConfig({ ...config, [field]: event.target.checked })} />{label}</label>)}
    </div><p className="muted">止损/止盈/回撤阈值为 0 时关闭对应规则。T+1 固定启用，最小交易单位100股。传统路径按运行器分数排序，缺少可比分数时按证券代码稳定排序；不承诺旧版混合排名一致。</p>
{step === 3 && <>    <details><summary>可选波段退出 · 默认关闭</summary><div className="form-grid">{([['trail_activate', '峰值涨幅达到后启用MA10退出'], ['time_stop_min_gain', '时间止损最低峰值涨幅'], ['breakeven_trigger', '峰值涨幅达到后启用保本障碍']] as const).map(([field, label]) => <label key={field}><span>{label}</span><input value={config[field]} onChange={event => setConfig({ ...config, [field]: event.target.value })} /></label>)}<label><span>时间止损观察日数，0关闭</span><input type="number" min={0} max={240} value={config.time_stop_days} onChange={event => setConfig({ ...config, time_stop_days: Number(event.target.value) })} /></label></div><p className="muted">比例0关闭对应激活。时间止损按入场之后已完成日线计数，需同时填写天数和最低峰值涨幅。仅以前一日完整可得高点确认激活；收盘跌破MA10或时间止损在后续开盘执行。保本障碍为入场成交价×1.002，仍扣费用和滑点，不保证净盈利；同根K线的新高不能倒推激活当天低点止损。</p></details>
    <details><summary>冻结交易费用与滑点</summary><div className="form-grid">{Object.entries(config.fee_config).map(([field, value]) => <label key={field}><span>{({ commission_rate: '佣金比例', minimum_commission: '最低佣金', sell_stamp_rate: '卖出印花税比例', transfer_rate: '过户费比例', cash_buffer: '保留现金', slippage_rate: '单边不利滑点比例 0–0.05' } as Record<string, string>)[field] || field}</span><input value={value} onChange={event => setConfig({ ...config, fee_config: { ...config.fee_config, [field]: event.target.value } })} /></label>)}</div></details></>}</section>}
      <div className="research-step-panel" hidden={step !== 4}><h4>核对并创建</h4><div className="period-summary"><span>名称：{name}</span><span>信号路径：{modeNames[mode]}</span><span>研究样本：{datasetIds.length} 个</span><span>资金：{config?.initial_capital || '—'}</span><span>日期：{start || '自动'} → {end || '自动'}</span></div>
    <div className="alert"><strong>研究范围与成交假设</strong><p>这是手工选定的固定研究样本，滚动股票池也仅在样本内变化。历史市场成分、退市与复权未经核验，结果不代表无幸存者偏差的全市场策略。</p><p>时点严格模式仅约束日线可得时间。所有买入都在信号之后的开盘；预设止损止盈按日线高低价模拟，缺少盘中先后顺序，默认双触发先止损。回撤减仓和收盘走弱清仓在后续开盘执行。</p><p>资金顺序：开盘退出 → 开盘买入 → 盘中风险退出。盘中卖出款不能用于同日开盘买入。期末持仓保留并按最后已知收盘价计值。</p></div>
    <div className="toolbar" style={{ marginTop: 16 }}><button className="button secondary" disabled={busy || !datasetIds.length || !config} onClick={() => perform(async () => { const value = await api<Omit<Preview, 'key'>>('/research/portfolios/preview', 'POST', body); if (alive.current) setPreview({ ...value, key }) })}>预览组合冻结计划</button><button className="button" disabled={busy || !checked} onClick={() => perform(async () => { const run = await api<Run>('/research/portfolios', 'POST', { ...body, name, expected_preview_sha256: checked?.preview_sha256 }); await refresh(); await choose(run.id) })}>确认创建组合回测</button></div>
    {checked && <section aria-label="组合冻结计划"><h4>冻结计划已准备</h4><p>{datasetIds.length} 个固定研究样本 · {String(checked.frozen_context.total_days)} 个交易日期 · {String(checked.frozen_context.start_date)} → {String(checked.frozen_context.end_date)}</p><details><summary>核对参数、版本、事件模板和资源预算</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify(checked.frozen_context, null, 2)}</pre></details></section>}
</div>
      <div className="research-step-actions"><button className="button secondary" disabled={step === 0} onClick={() => setStep(value => value - 1)}>上一步</button><span className="muted">{step + 1} / {steps.length} · 配置未提交前可随时修改</span><button className="button primary" disabled={step === steps.length - 1} onClick={() => setStep(value => value + 1)}>下一步</button></div>
    </div>
    <div className="research-pane" role="tabpanel" id="portfolio-panel-history" aria-labelledby="portfolio-tab-history" hidden={panel !== 'history'}>
    <h4>组合任务历史</h4><div className="table-wrap"><table aria-label="组合任务历史"><thead><tr><th>名称 / 路径</th><th>状态 / 进度</th><th>样本数</th><th>操作</th></tr></thead><tbody>{jobs.map(job => <tr key={job.id}><td>{job.name}<br /><small>{modeNames[job.mode]}</small></td><td>{states[job.state] || job.state} · {job.completed_days}/{job.total_days}</td><td>{job.symbol_count}</td><td><button className="button secondary" disabled={busy} onClick={() => perform(() => choose(job.id))}>查看组合</button></td></tr>)}</tbody></table></div>
{!jobs.length && <p className="muted">暂无组合任务。到配置组合创建一次运行。</p>}</div>
    <div className="research-pane" role="tabpanel" id="portfolio-panel-result" aria-labelledby="portfolio-tab-result" hidden={panel !== 'result'}>{!selected && <p className="muted">请在任务历史中选择组合，或先创建回测。</p>}
    {selected && <section aria-label="组合结果" style={{ marginTop: 20 }}><h4>{selected.name} · {states[selected.state] || selected.state}</h4><p>已完成 {selected.completed_days}/{selected.total_days} 日期 · {selected.chunk_count} 个检查点 · {(selected.elapsed_ms / 1000).toFixed(1)} 秒计算</p>{selected.state === 'succeeded' && <AIContextButton source={{ page: 'portfolio', artifact: { type: 'portfolio', id: selected.id }, label: selected.name }} />}{selected.error && <p className="alert error">{selected.error}</p>}
      <div className="toolbar">{(['pause', 'resume', 'cancel', 'retry'] as const).map(action => selected.capabilities[action] && <button key={action} className="button secondary" disabled={busy} onClick={() => perform(() => control(selected.id, action))}>{({ pause: '暂停组合', resume: '续跑组合', cancel: '取消组合', retry: '从已存检查点重试' })[action]}</button>)}<button className="button secondary" disabled={busy || !selected.chunk_count} onClick={() => perform(loadResult)}>加载组合曲线与成交证据</button>{selected.state === 'succeeded' && <ResearchTradeDownloads kind="portfolio" id={selected.id} />}<a className="button secondary" href={`/api/v1/research/portfolios/${selected.id}/export.json`} download>导出组合 JSON</a>{selected.capabilities.delete && <button className="button secondary" disabled={busy} onClick={() => setDeleteId(selected.id)}>删除组合</button>}</div>
      {deleteId === selected.id && <p className="alert">从历史列表删除，审计与检查点保留。<button className="button danger" disabled={busy} onClick={() => perform(() => control(selected.id, 'delete'))}>确认删除组合</button><button className="button secondary" onClick={() => setDeleteId('')}>保留组合</button></p>}
      <div className="form-grid"><p>期末资产 <strong>{selected.summary.ending_assets}</strong></p><p>总收益 <strong>{pct(selected.summary.total_return)}</strong></p><p>最大回撤 <strong>{pct(selected.summary.max_drawdown)}</strong></p><p>买入 {selected.summary.buy_count} / 卖出腿 {selected.summary.sell_count} / 手续费 {selected.summary.total_fees}</p></div>
      <p className="muted">质量标记：{selected.summary.quality_flags.join(' · ')}</p><details><summary>冻结配置、检查点摘要与保留持仓</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify({ frozen_context: selected.frozen_context, open_positions: selected.summary.open_positions, checkpoint_sha256: selected.checkpoint_sha256, result_sha256: selected.result_sha256 }, null, 2)}</pre></details>
    </section>}
    {detail?.result && <section aria-label="组合成交证据" style={{ marginTop: 20 }}><h4>已加载至 {detail.completed_days} 个日期的冻结证据</h4>{curve.length > 0 && <svg role="img" aria-label="组合权益曲线" viewBox="0 0 780 175" style={{ width: '100%', maxHeight: 220 }}><title>组合权益，{curve[0].date} 至 {curve[curve.length - 1].date}</title><path d={chart} transform="translate(10 5)" stroke="var(--chart-series1)" strokeWidth="2" fill="none" /></svg>}
      <h5>成交与资金顺序</h5><div className="table-wrap"><table aria-label="组合成交列表"><thead><tr><th>日期 / 时段</th><th>证券 / 方向</th><th>数量 / 成交价</th><th>费用 / 实现盈亏</th><th>原因 / 知识时间</th></tr></thead><tbody>{trades.slice(tradePage * 50, tradePage * 50 + 50).map((trade, index) => <tr key={index}><td>{trade.date}<br />{trade.phase === 'open' ? '开盘' : '日内时序未知'}</td><td>{trade.symbol} · {trade.side === 'buy' ? '买入' : '卖出'}</td><td>{trade.quantity} / {trade.price}<br /><small>参考 {trade.reference_price}</small></td><td>{trade.fees} / {trade.realized_pnl ?? '—'}</td><td>{reasons[trade.reason] || trade.reason}<br /><small>{trade.known_at || '未确认 / 日内预设触发'}</small><details><summary>成交依据</summary><pre style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify(trade, null, 2)}</pre></details></td></tr>)}</tbody></table></div><div className="toolbar"><button className="button secondary" disabled={tradePage === 0} onClick={() => setTradePage(value => value - 1)}>上一页成交</button><span>{trades.length} 笔，共 {Math.max(1, Math.ceil(trades.length / 50))} 页，当前 {tradePage + 1}</span><button className="button secondary" disabled={(tradePage + 1) * 50 >= trades.length} onClick={() => setTradePage(value => value + 1)}>下一页成交</button></div>
      <h5>样本内股票池轨迹</h5><label><span>组合股票池日期</span><select value={poolDate} onChange={event => setPoolDate(event.target.value)}>{detail.result.pool_history.map(item => <option key={item.date} value={item.date}>{item.date} · {item.members.length} 个成员</option>)}</select></label>{pool && <><p>依据 {pool.source_date} 日及更早的已知信息，决策时间 {pool.decision_at}</p><div className="table-wrap"><table aria-label="组合股票池信号"><thead><tr><th>证券</th><th>入池</th><th>分数</th><th>S1–S9 / 传统证据</th></tr></thead><tbody>{pool.rows.map(row => <tr key={row.symbol}><td>{row.symbol}</td><td>{row.in_pool ? '是' : '否'}<br /><small>{row.reason}</small></td><td>{row.score?.toFixed(2) ?? '—'}</td><td><PoolComponents value={row.components} /></td></tr>)}</tbody></table></div></>}
      <details><summary>每日现金、持仓估值及未成交原因</summary><pre style={{ whiteSpace: 'pre-wrap', maxHeight: 400, overflow: 'auto' }}>{JSON.stringify({ equity: detail.result.equity, decisions: detail.result.decisions.map(item => ({ ...item, reason: reasons[item.reason] || item.reason })) }, null, 2)}</pre></details>
    </section>}
{selected?.state === 'succeeded' && <div className="research-next-actions" aria-label="组合后续研究"><button className="button secondary" onClick={() => (onNavigate || navigateResearch)({ view: 'analysis', sourceId: selected.id })}>查看高级分析与条件计划</button><button className="button secondary" onClick={() => (onNavigate || navigateResearch)({ view: 'experiments', mode: 'portfolio', sourceId: selected.id })}>用此组合创建参数实验</button><button className="button secondary" onClick={() => (onNavigate || navigateResearch)({ view: 'experiments', mode: 'portfolio-wf', sourceId: selected.id })}>用此组合创建 Walk-forward</button><button className="button secondary" onClick={() => (onNavigate || navigateResearch)({ view: 'reports', mode: 'portfolio', sourceId: selected.id })}>保存到组合报告库</button></div>}</div>
  </section>
}
