import { useEffect, useRef, useState } from 'react'
import { api, apiUpload } from './api'

type Row = Record<string, unknown>
type Summary = { initial_capital: string; ending_assets: string; total_return: string; max_drawdown: string; buy_count: number; sell_count: number; total_fees: string; realized_pnl: string; quality_flags: string[] }
type Payload = { title: string; created_at: string; source: Row; input: { mode: string; version: string; params: Row; config: Row; event_profile: unknown; code_sha256: string; datasets: Array<{ symbol: string; dataset_id: string; bars_sha256: string; bars: Row[] }> }; summary: Summary & { limitations: string[]; open_positions: Row }; chunks: Array<{ ordinal: number; prior_sha256: string; result_sha256: string; result: { equity: Array<{ date: string; total_assets: string; cash: string }>; trades: Row[]; pool_history: Array<{ date: string; source_date: string; members: string[]; rows: Row[] }>; decisions: Row[] } }> }
type Report = { id: string; title: string; origin: string; content_sha256: string; source_run_id: string; created_at: string; mode: string; strategy_id: string; strategy_version: string; symbol_count: number; first_date: string; last_date: string; checkpoint_count: number; summary: Summary; payload?: Payload }
const pct = (value: string) => `${(Number(value) * 100).toFixed(2)}%`
const show = (value: unknown) => value == null ? '未知' : typeof value === 'object' ? JSON.stringify(value) : String(value)

export function PortfolioReportLibrary({ sourceRunId }: { sourceRunId?: string }) {
  const [reports, setReports] = useState<Report[]>([])
  const [selected, setSelected] = useState<Report | null>(null)
  const [title, setTitle] = useState('完整组合报告')
  const [file, setFile] = useState<File | null>(null)
  const [deleteId, setDeleteId] = useState('')
  const [page, setPage] = useState(0)
  const [poolDate, setPoolDate] = useState('')
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [busy, setBusy] = useState(false)
  const live = useRef(true), input = useRef<HTMLInputElement>(null), request = useRef(0)
  async function refresh() { const items = await api<Report[]>('/research/portfolio-reports'); if (live.current) setReports(items) }
  useEffect(() => { live.current = true; refresh().catch(err => { if (live.current) setError(err.message) }); return () => { live.current = false } }, [])
  useEffect(() => { if (sourceRunId) setTitle(`完整组合报告 · ${sourceRunId.slice(0, 8)}`) }, [sourceRunId])
  async function perform(action: () => Promise<void>) { if (busy) return; setBusy(true); setError(''); setNotice(''); try { await action() } catch (err) { if (live.current) setError(err instanceof Error ? err.message : String(err)) } finally { if (live.current) setBusy(false) } }
  function select(report: Report) { setSelected(report); setPage(0); setPoolDate(report.payload?.chunks.flatMap(item => item.result.pool_history)[0]?.date || ''); setDeleteId('') }
  const payload = selected?.payload
  const equity = payload?.chunks.flatMap(chunk => chunk.result.equity) || []
  const trades = payload?.chunks.flatMap(chunk => chunk.result.trades) || []
  const pools = payload?.chunks.flatMap(chunk => chunk.result.pool_history) || []
  const pool = pools.find(row => row.date === poolDate)
  const values = equity.map(row => Number(row.total_assets)), low = Math.min(...values), high = Math.max(...values)
  const path = values.map((value, index) => `${index ? 'L' : 'M'} ${index * 760 / Math.max(1, values.length - 1)} ${150 - (value - low) / Math.max(1, high - low) * 140}`).join(' ')
  return <section className="card" aria-label="组合报告库" style={{ marginTop: 24 }}><h3>完整组合报告库</h3><p className="muted">冻结3条组合路径的输入日线、策略参数、事件模板、现金持仓、成交、股票池和原始检查点摘要。报告随数据库备份保存，来源任务删除后仍可查看。</p>
    <p className="muted">完整 ZIP 同时包含校验清单、JSON、离线 HTML 与 Excel，压缩包及解压总量均限16MiB。超过限制时明确拒绝，不截断数据。导入不会重新计算策略或创建交易；包内摘要用于完整性核对，不认证第三方绩效。</p>
    {error && <p className="alert error" role="alert">{error}</p>}{notice && <p className="alert success" role="status">{notice}</p>}
    {sourceRunId ? <div className="form-grid"><label><span>组合报告标题</span><input maxLength={120} value={title} onChange={event => setTitle(event.target.value)} /></label><div className="form-actions"><button className="button" disabled={busy || !title.trim()} onClick={() => perform(async () => { const saved = await api<Report>('/research/portfolio-reports', 'POST', { portfolio_run_id: sourceRunId, title: title.trim() }); await refresh(); if (live.current) { select(saved); setNotice('完整组合报告已冻结。') } })}>将当前组合保存为报告</button></div></div> : <p className="muted">选择已成功完成的组合任务后，可冻结报告。</p>}
    <details style={{ marginTop: 16 }}><summary>导入完整组合报告包</summary><label><span>组合报告 ZIP 文件</span><input ref={input} type="file" accept=".zip,application/zip" disabled={busy} onChange={event => setFile(event.target.files?.[0] || null)} /></label><button className="button secondary" disabled={busy || !file} onClick={() => perform(async () => { if (!file) return; if (file.size > 16 * 1024 * 1024) throw new Error('组合报告包超过16MiB。'); const value = await apiUpload<Report>('/research/portfolio-reports/import', file); await refresh(); if (live.current) { select(value); setFile(null); if (input.current) input.current.value = ''; setNotice('组合报告已校验并导入，未重新计算。') } })}>校验并导入组合报告</button></details>
    <div className="toolbar" style={{ marginTop: 16 }}><button className="button secondary" disabled={busy} onClick={() => perform(refresh)}>刷新组合报告库</button><span>{reports.length} 份组合报告</span></div>
    <div className="table-wrap"><table aria-label="组合报告目录"><thead><tr><th>标题 / 路径</th><th>样本 / 区间</th><th>收益 / 回撤</th><th>来源</th><th>操作</th></tr></thead><tbody>{reports.map(report => <tr key={report.id}><td>{report.title}<br /><small>{report.mode}</small></td><td>{report.symbol_count} 个证券<br />{report.first_date} → {report.last_date}</td><td>{pct(report.summary.total_return)} / {pct(report.summary.max_drawdown)}</td><td>{report.origin === 'import' ? '导入，未重新计算' : '本地冻结'}</td><td><button className="button secondary" disabled={busy} onClick={() => perform(async () => { const token = ++request.current; const value = await api<Report>(`/research/portfolio-reports/${report.id}`); if (live.current && token === request.current) select(value) })}>查看组合报告</button><button className="button secondary" disabled={busy} onClick={() => setDeleteId(report.id)}>删除组合报告</button></td></tr>)}</tbody></table></div>
    {deleteId && <div className="alert"><p>删除此组合报告的列表记录？原组合任务及审计快照保留。</p><button className="button danger" disabled={busy} onClick={() => perform(async () => { const id = deleteId; await api(`/research/portfolio-reports/${id}`, 'DELETE', {}); await refresh(); if (live.current) { if (selected?.id === id) setSelected(null); setDeleteId('') } })}>确认删除组合报告</button><button className="button secondary" disabled={busy} onClick={() => setDeleteId('')}>保留组合报告</button></div>}
    {selected && payload && <section aria-label="组合报告详情" style={{ marginTop: 20 }}><h4>{selected.title}</h4><p>{selected.origin === 'import' ? '导入快照，未重新计算' : '本地已完成组合快照'} · {selected.symbol_count} 个证券 · {selected.checkpoint_count} 个原始检查点</p><div className="toolbar" style={{ flexWrap: 'wrap' }}>{[['export.zip', '下载完整组合 ZIP'], ['report.html', '下载组合离线 HTML'], ['export.xlsx', '下载组合 Excel']].map(([suffix, label]) => <a key={suffix} className="button secondary" href={`/api/v1/research/portfolio-reports/${selected.id}/${suffix}`} download>{label}</a>)}</div>
      <div className="form-grid"><p>期初 {selected.summary.initial_capital} → 期末 {selected.summary.ending_assets}</p><p>收益 {pct(selected.summary.total_return)} · 回撤 {pct(selected.summary.max_drawdown)}</p><p>买入 {selected.summary.buy_count} / 卖出腿 {selected.summary.sell_count} / 费用 {selected.summary.total_fees}</p></div>
      {equity.length > 0 && <svg role="img" aria-label="冻结组合报告权益曲线" viewBox="0 0 760 165" style={{ width: '100%', maxHeight: 220 }}><path d={path} fill="none" stroke="var(--chart-series1)" strokeWidth="2.5" /></svg>}
      <p className="muted">{payload.summary.limitations.join('；')}</p><p className="muted">质量标记：{selected.summary.quality_flags.join(' · ')}</p>
      {'analysis' in payload && <details><summary>已冻结高级分析、Bootstrap假设与日终条件计划</summary><p className="muted">这是报告创建时保存的分析版本，不会随现行算法更新；条件计划不是成交或真实委托。</p><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', maxHeight: 600, overflow: 'auto' }}>{JSON.stringify(payload.analysis, null, 2)}</pre></details>}
      <details><summary>冻结参数、模板、保留持仓与源代码版本</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify({ params: payload.input.params, config: payload.input.config, event_profile: payload.input.event_profile, open_positions: payload.summary.open_positions, source: payload.source, protocol: payload.input.version, code_sha256: payload.input.code_sha256 }, null, 2)}</pre></details>
      <h5>冻结成交 · {trades.length} 笔</h5><div className="table-wrap"><table aria-label="冻结组合报告成交"><thead><tr><th>日期 / 证券</th><th>方向 / 阶段</th><th>数量 / 价格</th><th>费用 / 盈亏</th><th>已知时间 / 原因</th></tr></thead><tbody>{trades.slice(page * 50, page * 50 + 50).map((trade, index) => <tr key={index}><td>{show(trade.date)}<br />{show(trade.symbol)}</td><td>{trade.side === 'buy' ? '买入' : '卖出'}<br />{trade.phase === 'open' ? '开盘' : '日内顺序未知'}</td><td>{show(trade.quantity)} / {show(trade.price)}<br /><small>参考 {show(trade.reference_price)} · 滑点 {show(trade.slippage_rate)}</small></td><td>{show(trade.fees)} / {show(trade.realized_pnl)}</td><td>{show(trade.known_at)}<br />{show(trade.reason)}<details><summary>完整成交依据</summary><pre style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify(trade, null, 2)}</pre></details></td></tr>)}</tbody></table></div><div className="toolbar"><button className="button secondary" disabled={page === 0} onClick={() => setPage(value => value - 1)}>报告成交上一页</button><span>第 {page + 1} / {Math.max(1, Math.ceil(trades.length / 50))} 页</span><button className="button secondary" disabled={(page + 1) * 50 >= trades.length} onClick={() => setPage(value => value + 1)}>报告成交下一页</button></div>
      <h5>冻结股票池和事件证据</h5><label><span>报告股票池日期</span><select value={poolDate} onChange={event => setPoolDate(event.target.value)}>{pools.map(row => <option key={row.date} value={row.date}>{row.date} · {row.members.length} 成员</option>)}</select></label>{pool && <details><summary>{pool.date} 的完整池依据</summary><pre style={{ whiteSpace: 'pre-wrap', maxHeight: 400, overflow: 'auto' }}>{JSON.stringify(pool, null, 2)}</pre></details>}
      <details><summary>输入数据与原始检查点摘要</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify({ content_sha256: selected.content_sha256, datasets: payload.input.datasets.map(item => ({ symbol: item.symbol, dataset_id: item.dataset_id, bars: item.bars.length, bars_sha256: item.bars_sha256 })), chunks: payload.chunks.map(({ result: _, ...chunk }) => chunk) }, null, 2)}</pre></details>
    </section>}
  </section>
}
