import { useEffect, useRef, useState } from 'react'
import { api } from './api'
import { useTaskDeepLink } from './task-deep-link'

type Row = Record<string, unknown>
type PlanRow = { symbol: string; side: string; status: string; reason: string; quantity_if_executable: number | null; price: null; reference_threshold?: string; source_date: string; known_at: string | null; remaining_observed_bars: number | null; conditions: string[]; components: Row }
type Result = { risk: Row; stability: Row & { months: Row[]; neighborhood: { reason: string }; scope: string }; regimes: { buckets: Row[]; scope: string }; monte_carlo: Row & { scope: string; status: string; reason: string | null }; methodology: Row; completed_trades: Row[]; open_cycles: Row[]; quality_flags: string[]; daily_plan: { status: string; reason?: string; as_of_date: string; decision_cutoff?: string; scope?: string; holdings?: Row[]; plan_signals?: PlanRow[]; open_signals?: PlanRow[]; risk_order?: string }; daily_detail: { date: string; trades: Row[]; equity: Row; decisions: Row[] } }
type Analysis = { id: string; name: string; source_run_id: string; source_result_sha256: string; state: string; result_sha256: string | null; code_sha256: string; version: string; options: { seed: number; iterations: number; block_size: number; plan_date: string }; error: string | null; capabilities: Record<string, boolean>; result?: Result }
type Source = { id: string; name: string; state: string; frozen_context?: { start_date: string; end_date: string } }
const stateNames: Record<string, string> = { queued: '排队', running: '分析中', paused: '已暂停，需重新开始计算', succeeded: '已完成', failed: '失败', cancelled: '已取消', cancelling: '取消中' }
const planNames: Record<string, string> = { conditional_next_open: '下次开盘条件计划', conditional_price_barrier: '未来价格触发情景', waiting_observed_bars: '等待延迟日线', waiting_available_history: '等待可得行情', invalidated_asof: '当前已失效' }
const show = (value: unknown) => value === null || value === undefined ? '未生成 / 不适用' : typeof value === 'object' ? JSON.stringify(value) : String(value)
const percent = (value: unknown) => value == null ? '未生成' : `${(Number(value) * 100).toFixed(2)}%`
const riskLabels: Record<string, string> = { daily_sample_count: '日收益样本数', completed_trade_count: '完整清仓周期数', annualized_return: '按观察日年化收益', sharpe: 'Sharpe', sortino: 'Sortino', calmar: 'Calmar', max_drawdown: '最大回撤', profit_factor: '完整周期盈亏比', expectancy: '完整周期期望收益', average_win: '平均盈利周期收益', average_loss: '平均亏损周期收益', average_net_pnl: '平均完整周期净盈亏', max_consecutive_losses: '最多连续亏损周期', fill_rate: '到期意图成交率', eligible_entry_attempts: '可执行买入意图数', executed_entries: '实际买入数', max_concurrent_positions: '最高同时持仓证券数' }
const ratios = new Set(['annualized_return', 'max_drawdown', 'expectancy', 'average_win', 'average_loss', 'fill_rate'])

function Rows({ rows, label }: { rows: Row[]; label: string }) {
  return rows.length ? <div className="table-wrap"><table aria-label={label}><thead><tr>{Object.keys(rows[0]).map(key => <th key={key}>{key}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{Object.keys(rows[0]).map(key => <td key={key}>{show(row[key])}</td>)}</tr>)}</tbody></table></div> : <p className="muted">无记录</p>
}

export function PortfolioAnalysisWorkspace({ sourceRunId }: { sourceRunId?: string }) {
  const [sources, setSources] = useState<Source[]>([]), [source, setSource] = useState(sourceRunId || '')
  const [sourceDetail, setSourceDetail] = useState<Source | null>(null)
  const [name, setName] = useState('组合高级分析'), [seed, setSeed] = useState(20260926), [iterations, setIterations] = useState(400), [blockSize, setBlockSize] = useState(5), [planDate, setPlanDate] = useState('')
  const [runs, setRuns] = useState<Analysis[]>([]), [selected, setSelected] = useState<Analysis | null>(null)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [deleteId, setDeleteId] = useState(''), [cyclePage, setCyclePage] = useState(0)
  const [reportId, setReportId] = useState('')
  const alive = useRef(true), selectedId = useRef(''), sourceToken = useRef(0)
  async function refresh() { const [rows, values] = await Promise.all([api<Analysis[]>('/research/portfolio-analyses'), api<Source[]>('/research/portfolios')]); if (alive.current) { setRuns(rows); setSources(values.filter(item => item.state === 'succeeded')) } }
  async function choose(id: string) { selectedId.current = id; setReportId(''); setDeleteId(''); setCyclePage(0); const row = await api<Analysis>(`/research/portfolio-analyses/${id}`); if (alive.current && selectedId.current === id) setSelected(row) }
  useEffect(() => { alive.current = true; refresh().catch(err => { if (alive.current) setError(err.message) }); return () => { alive.current = false } }, [])
  useEffect(() => { if (sourceRunId) setSource(sourceRunId) }, [sourceRunId])
  useEffect(() => { setSourceDetail(null); if (!source) return; const token = ++sourceToken.current; api<Source>(`/research/portfolios/${source}`).then(row => { if (alive.current && token === sourceToken.current) { setSourceDetail(row); setPlanDate(row.frozen_context?.end_date || '') } }).catch(err => { if (alive.current && token === sourceToken.current) setError(err.message) }) }, [source])
  const active = runs.some(row => ['queued', 'running', 'cancelling'].includes(row.state))
  useEffect(() => { if (!active) return; let pending = false; const timer = setInterval(async () => { if (pending) return; pending = true; try { await refresh(); const id = selectedId.current; if (id) { const row = await api<Analysis>(`/research/portfolio-analyses/${id}`); if (alive.current && selectedId.current === id) setSelected(row) } } catch (err) { if (alive.current) setError(err instanceof Error ? err.message : String(err)) } finally { pending = false } }, 1500); return () => clearInterval(timer) }, [active])
  useTaskDeepLink('portfolio_analysis', choose, '[aria-label="组合高级分析详情"]', setError)
  async function perform(work: () => Promise<void>) { if (busy) return; setBusy(true); setError(''); try { await work() } catch (err) { if (alive.current) setError(err instanceof Error ? err.message : String(err)) } finally { if (alive.current) setBusy(false) } }
  async function control(id: string, action: string) { await api(`/research/portfolio-analyses/${id}${action === 'delete' ? '' : '/' + action}`, action === 'delete' ? 'DELETE' : 'POST', {}); if (action === 'delete') { selectedId.current = ''; setSelected(null); setDeleteId('') } else await choose(id); await refresh() }
  const result = selected?.result, plan = result?.daily_plan
  return <section className="card" aria-label="组合高级分析" style={{ marginTop: 24 }}>
    <div className="section-header"><div><h3>组合高级分析与日终计划</h3><p className="muted">对已完成组合的实际资金曲线和成交做描述统计，冻结版本与随机种子；计划仅使用所选日期当日已可得信息。</p></div><button className="button secondary" disabled={busy} onClick={() => perform(refresh)}>刷新组合分析</button></div>
    <p className="alert">Bootstrap 对组合每日收益分块抽样，保留块内顺序，假设块之间独立；不能预测未来，也不替代独立 Walk-forward。交易指标按完整持仓周期统计，部分退出会合并，期末持仓不会伪造成交。</p>
    {error && <p className="alert error" role="alert">{error}</p>}
    <div className="form-grid"><label><span>分析来源组合</span><select value={source} onChange={event => setSource(event.target.value)}><option value="">选择已完成组合</option>{sources.map(row => <option key={row.id} value={row.id}>{row.name} · {row.id.slice(0, 8)}</option>)}</select></label><label><span>组合分析名称</span><input maxLength={80} value={name} onChange={event => setName(event.target.value)} /></label>
      <label><span>Bootstrap 随机种子</span><input type="number" min={0} max={4294967295} value={seed} onChange={event => setSeed(Number(event.target.value))} /></label><label><span>Bootstrap 抽样次数</span><input type="number" min={100} max={2000} value={iterations} onChange={event => setIterations(Number(event.target.value))} /></label><label><span>Bootstrap 区块日数</span><input type="number" min={1} max={60} value={blockSize} onChange={event => setBlockSize(Number(event.target.value))} /></label>
      <label><span>持仓与条件计划日期</span><input type="date" min={sourceDetail?.frozen_context?.start_date} max={sourceDetail?.frozen_context?.end_date} value={planDate} onChange={event => setPlanDate(event.target.value)} /></label></div>
    <p className="muted">风险指标使用原组合全部区间；持仓和次日条件计划使用指定日期。最多2000次抽样，每项任务限120秒、512MiB；与其他回测共用计算队列。中断后可显式重新计算。</p>
    <button className="button" disabled={busy || !source || !name.trim() || !planDate} onClick={() => perform(async () => { const row = await api<Analysis>('/research/portfolio-analyses', 'POST', { source_run_id: source, name: name.trim(), seed, iterations, block_size: blockSize, plan_date: planDate }); await refresh(); await choose(row.id) })}>创建组合分析与条件计划</button>
    <h4>组合分析历史</h4><div className="table-wrap"><table aria-label="组合分析历史"><thead><tr><th>名称 / 来源</th><th>状态</th><th>抽样与计划日期</th><th>操作</th></tr></thead><tbody>{runs.map(row => <tr key={row.id}><td>{row.name}<br /><small>{row.source_run_id.slice(0, 8)}</small></td><td>{stateNames[row.state] || row.state}</td><td>{row.options.iterations} 次 · 区块{row.options.block_size}日<br />{row.options.plan_date}</td><td><button className="button secondary" disabled={busy} onClick={() => perform(() => choose(row.id))}>查看组合分析</button></td></tr>)}</tbody></table></div>
    {selected && <section aria-label="组合高级分析详情"><h4>{selected.name} · {stateNames[selected.state] || selected.state}</h4>{selected.error && <p className="alert error">{selected.error}</p>}<div className="toolbar">{(['resume', 'retry', 'cancel'] as const).filter(action => selected.capabilities[action]).map(action => <button key={action} className="button secondary" disabled={busy} onClick={() => perform(() => control(selected.id, action))}>{({ resume: '恢复组合分析', retry: '重试组合分析', cancel: '取消组合分析' })[action]}</button>)}<a className="button secondary" href={`/api/v1/research/portfolio-analyses/${selected.id}/export.json`} download>导出组合分析 JSON</a>{selected.capabilities.delete && <button className="button secondary" disabled={busy} onClick={() => setDeleteId(selected.id)}>删除组合分析</button>}</div>
      {deleteId === selected.id && <div className="alert"><p>删除分析目录记录，原组合和已冻结报告保留。</p><button className="button danger" disabled={busy} onClick={() => perform(() => control(selected.id, 'delete'))}>确认删除组合分析</button><button className="button secondary" onClick={() => setDeleteId('')}>保留组合分析</button></div>}
      {result && <><h5>组合风险 · 全区间实际权益</h5><div className="table-wrap"><table aria-label="组合风险指标"><thead><tr><th>指标</th><th>值</th></tr></thead><tbody>{Object.entries(riskLabels).map(([key, title]) => <tr key={key}><td>{title}</td><td>{ratios.has(key) ? percent(result.risk[key]) : show(result.risk[key])}</td></tr>)}</tbody></table></div><details><summary>恢复期与空值原因</summary><pre style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify({ recovery: result.risk.recovery, unavailable_reasons: result.risk.unavailable_reasons }, null, 2)}</pre></details>
        <h5>稳定性和行情分组</h5><p className="muted">{result.stability.scope}。{result.stability.neighborhood.reason}</p><p>周期数量惩罚 {show(result.stability.trade_count_penalty)} / 月收益波动惩罚 {show(result.stability.return_variance_penalty)} / 月收益标准差 {percent(result.stability.monthly_return_std)}</p><Rows rows={result.stability.months} label="组合月度收益" /><p className="muted">{result.regimes.scope}</p><Rows rows={result.regimes.buckets} label="组合行情分组" />
        <h5>组合日收益区块 Bootstrap</h5><p className="muted">{result.monte_carlo.scope}</p><p>{result.monte_carlo.status === 'generated' ? '已生成' : '样本不足'} · {String(result.monte_carlo.sample_count)}个日收益 · 种子{String(result.monte_carlo.seed)} · {String(result.monte_carlo.iterations)}次 / 区块{String(result.monte_carlo.block_size)}日</p>{result.monte_carlo.reason && <p className="alert">{result.monte_carlo.reason}</p>}<Rows label="组合 Bootstrap 分位数" rows={['total_return', 'max_drawdown'].map(key => ({ 指标: key === 'total_return' ? '抽样总收益' : '抽样最大回撤', p5: percent((result.monte_carlo[key] as Row | null)?.p5), p50: percent((result.monte_carlo[key] as Row | null)?.p50), p95: percent((result.monte_carlo[key] as Row | null)?.p95) }))} /><p>抽样归零比例 {percent(result.monte_carlo.ruin_probability)} · 抽样亏损至少20%比例 {percent(result.monte_carlo.capital_loss_20_probability)}</p>
        <h5>{result.daily_detail.date} 日冻结持仓和成交</h5><p>日终资产 {show(result.daily_detail.equity.total_assets)} · 现金 {show(result.daily_detail.equity.cash)} · 持仓证券 {show(result.daily_detail.equity.position_count)}</p><Rows rows={plan?.holdings || Object.entries((result.daily_detail.equity.positions || {}) as Record<string, Row>).map(([symbol, row]) => ({ symbol, ...row }))} label="组合指定日持仓" /><details><summary>当日成交和未执行原因</summary><pre style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify({ trades: result.daily_detail.trades, decisions: result.daily_detail.decisions }, null, 2)}</pre></details>
        <h5>下一观察时点条件计划</h5>{plan?.status !== 'generated' ? <p className="alert">未生成：{plan?.reason}</p> : <><p className="alert">{plan.scope}</p><p>信息截止 {plan.decision_cutoff}。{plan.risk_order}</p><div className="table-wrap"><table aria-label="组合条件计划"><thead><tr><th>证券 / 方向</th><th>状态 / 原因</th><th>条件数量 / 阈值</th><th>来源 / 剩余观察日线</th><th>执行前条件</th></tr></thead><tbody>{plan.plan_signals?.map((row, i) => <tr key={i}><td>{row.symbol} / {row.side === 'buy' ? '买入' : '卖出'}</td><td>{planNames[row.status] || row.status}<br />{row.reason}</td><td>{row.quantity_if_executable ?? '开盘后计算'}<br />阈值 {row.reference_threshold || '—'}<br />成交价：未知</td><td>{row.source_date}<br />{row.remaining_observed_bars ?? '不适用'}<br /><small>{row.known_at || '历史可得时间未知或预设条件'}</small></td><td>{row.conditions.join('；')}<details><summary>信号依据</summary><pre style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify(row.components, null, 2)}</pre></details></td></tr>)}</tbody></table></div>{!plan.plan_signals?.length && <p className="muted">截止此日无候选或退出情景。</p>}</>}
        <h5>完整持仓周期 · {result.completed_trades.length} 个</h5><Rows rows={result.completed_trades.slice(cyclePage * 25, cyclePage * 25 + 25)} label="组合完整周期" /><div className="toolbar"><button className="button secondary" disabled={!cyclePage} onClick={() => setCyclePage(value => value - 1)}>周期上一页</button><span>{cyclePage + 1} / {Math.max(1, Math.ceil(result.completed_trades.length / 25))}</span><button className="button secondary" disabled={(cyclePage + 1) * 25 >= result.completed_trades.length} onClick={() => setCyclePage(value => value + 1)}>周期下一页</button></div>
        <details><summary>分析方法、质量和完整摘要</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify({ methodology: result.methodology, quality_flags: result.quality_flags, options: selected.options, version: selected.version, code_sha256: selected.code_sha256, source_result_sha256: selected.source_result_sha256, result_sha256: selected.result_sha256 }, null, 2)}</pre></details>
        <button className="button" disabled={busy} onClick={() => perform(async () => { const report = await api<{ id: string }>('/research/portfolio-reports', 'POST', { portfolio_run_id: selected.source_run_id, analysis_run_id: selected.id, title: `${selected.name} · 完整组合报告` }); if (alive.current) setReportId(report.id) })}>冻结含分析和条件计划的组合报告</button>{reportId && <p role="status">组合报告已冻结；可在报告库刷新查看。<a className="button secondary" href={`/api/v1/research/portfolio-reports/${reportId}/export.zip`} download>下载含分析完整 ZIP</a><a className="button secondary" href={`/api/v1/research/portfolio-reports/${reportId}/report.html`} target="_blank" rel="noreferrer">查看含分析离线 HTML</a></p>}
      </>}
    </section>}
  </section>
}
