import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import '@testing-library/jest-dom/vitest'
import { beforeEach, expect, it, vi } from 'vitest'
import { PortfolioWorkspace } from './portfolio-workspace'

const mockApi = vi.hoisted(() => vi.fn())
vi.mock('./api', () => ({ api: mockApi }))
vi.mock('./strategy-presets', () => ({ StrategyPresets: () => null }))
vi.mock('./ai-launcher', () => ({ AIContextButton: () => null }))
vi.mock('./research-table-downloads', () => ({ ResearchTradeDownloads: () => null }))
const id = 'a'.repeat(32), secondId = 'b'.repeat(32)
const defaults = { initial_capital: '100000', position_pct: '0.2', max_positions: 5, max_holding_bars: 10, top_n: 20, entry_top_k: 0, entry_delay_bars: 1, execution_strict: true, pool_roll: 'daily', stop_loss_pct: '0', take_profit_pct: '0', trailing_stop_pct: '0', intraday_trailing: false, trailing_reduce_ratio: '1', daily_weak_clear: false, weak_confirm_days: 1, invalidate_pending: true, ambiguity_policy: 'conservative', fee_config: { commission_rate: '0.0003' }, trail_activate: '0', time_stop_days: 0, time_stop_min_gain: '0', breakeven_trigger: '0' }
const run = { id, name: '历史组合', mode: 'matrix_raw_s1_s9', state: 'succeeded', completed_days: 10, total_days: 10, symbol_count: 1, chunk_count: 2, elapsed_ms: 200, summary: { ending_assets: '110000', total_return: '0.1', max_drawdown: '0.02', buy_count: 1, sell_count: 1, total_fees: '10', quality_flags: [], open_positions: {} }, capabilities: {}, result_sha256: 'sha', checkpoint_sha256: 'point' }
beforeEach(() => {
  window.history.replaceState(null, '', '/?page=research&research=portfolio')
  Element.prototype.scrollIntoView = vi.fn()
  mockApi.mockReset()
  mockApi.mockImplementation((path: string) => {
    if (path === '/market/datasets') return Promise.resolve([{ id: 'ds1', symbol: '600000', first_date: '2025-01-01', last_date: '2025-10-01', bar_count: 260, availability_quality: 'provided_availability' }])
    if (path === '/research/strategies') return Promise.resolve([])
    if (path === '/research/event-profiles') return Promise.resolve({ active_profile_id: 'system', profiles: [] })
    if (path === '/research/portfolios/schema') return Promise.resolve({ defaults, event_defaults: {}, event_schema: {} })
    if (path === '/research/portfolios/preview') return Promise.resolve({ preview_sha256: 'frozen', frozen_context: { total_days: 10, start_date: '2025-01-01', end_date: '2025-10-01' }, limitations: [] })
    if (path === '/research/portfolios') return Promise.resolve([run])
    if (path === `/research/portfolios/${id}`) return Promise.resolve(run)
    if (path === `/research/portfolios/${secondId}`) return Promise.resolve({ ...run, id: secondId, name: '第二条组合' })
    throw new Error(`Unexpected ${path}`)
  })
})
it('separates setup steps and retains edited inputs, while invalidating a stale preview', async () => {
  render(<PortfolioWorkspace />)
  const sample = await screen.findByRole('checkbox', { name: /组合样本 600000/ })
  fireEvent.click(sample)
  fireEvent.change(screen.getByLabelText('组合实验名称'), { target: { value: '未提交组合' } })
  expect(screen.queryByRole('textbox', { name: '组合初始资金' })).toBeNull()
  expect(screen.queryByRole('table', { name: '组合任务历史' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: /资金与执行/ }))
  fireEvent.change(screen.getByLabelText('组合初始资金'), { target: { value: '220000' } })
  expect(screen.queryByRole('textbox', { name: '预设止损比例 0–0.5' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: /预览提交/ }))
  fireEvent.click(screen.getByRole('button', { name: '预览组合冻结计划' }))
  await screen.findByRole('heading', { name: '冻结计划已准备' })
  expect(screen.getByRole('button', { name: '确认创建组合回测' })).toBeEnabled()
  expect(mockApi.mock.calls.find(call => call[0].endsWith('/preview'))?.[2]).toMatchObject({ dataset_ids: ['ds1'], config: { initial_capital: '220000' } })
  fireEvent.click(screen.getByRole('button', { name: /资金与执行/ }))
  expect(screen.getByLabelText('组合初始资金')).toHaveValue('220000')
  fireEvent.change(screen.getByLabelText('组合初始资金'), { target: { value: '230000' } })
  fireEvent.click(screen.getByRole('button', { name: /预览提交/ }))
  expect(screen.getByRole('button', { name: '确认创建组合回测' })).toBeDisabled()
  fireEvent.click(screen.getByRole('button', { name: /样本与日期/ }))
  expect(screen.getByLabelText('组合实验名称')).toHaveValue('未提交组合')
  expect(screen.getByRole('checkbox', { name: /组合样本 600000/ })).toBeChecked()
})
it('opens a result from history and hands the exact source to a separate downstream page', async () => {
  const navigate = vi.fn()
  render(<PortfolioWorkspace onNavigate={navigate} />)
  await screen.findByRole('checkbox', { name: /组合样本/ })
  fireEvent.click(screen.getByRole('tab', { name: /任务历史/ }))
  fireEvent.click(screen.getByRole('button', { name: '查看组合' }))
  await screen.findByRole('heading', { name: '历史组合 · 已完成' })
  expect(screen.getByRole('tab', { name: '运行结果' })).toHaveAttribute('aria-selected', 'true')
  expect(screen.queryByRole('table', { name: '组合任务历史' })).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: '用此组合创建参数实验' }))
  expect(navigate).toHaveBeenCalledWith({ view: 'experiments', mode: 'portfolio', sourceId: id })
  expect(mockApi.mock.calls.some(call => /portfolio-(analyses|reports|experiments|walk)/.test(call[0]))).toBe(false)
})
it('opens another deep-linked task in an already mounted workspace', async () => {
  window.history.replaceState(null, '', `/?page=backtest&task=portfolio:${id}`)
  render(<PortfolioWorkspace />)
  await screen.findByRole('heading', { name: '历史组合 · 已完成' })
  act(() => { window.history.pushState(null, '', `/?page=research&task=portfolio:${secondId}`); window.dispatchEvent(new Event('research-navigation')) })
  await screen.findByRole('heading', { name: '第二条组合 · 已完成' })
  await waitFor(() => expect(mockApi).toHaveBeenCalledWith(`/research/portfolios/${secondId}`))
})
