import { useEffect, useState } from 'react'
import { api } from './api'
import { ScanJobs } from './scan-jobs'
import type { EventProfileCatalog } from './event-profiles'

type Dataset = { id: string; symbol: string; first_date: string; last_date: string; availability_quality: string }
type Strategy = { enabled_in_rebuild?: boolean; default_in_rebuild?: boolean; id: string; name: string; signal_params: Record<string, string | number | boolean> | null; params_schema: Record<string, { title?: string; type: string; minimum?: number; maximum?: number; options?: string[]; enum?: string[] }>; capabilities: { supports_signal_age_filter: boolean; supports_entry_delay: boolean } }
type Scan = { id: string; as_of_date: string | null; date_from: string | null; date_to: string | null; signal_count: number; created_at: string }
type Sources = { trend_pools: Array<{ id: string; as_of_date: string }>; tdx_jobs: Array<{ id: string; as_of_date: string; total_count: number; error_count: number }>; notes: string[]; signal_context_strategies?: Strategy[] }
type Source = { kind: string; dataset_ids?: string[]; screener_run_id?: string; step?: string; tdx_job_id?: string }
type SourcePreview = { available_dataset_ids: string[]; available_count: number; selected_count: number; is_subset: boolean }
type Row = { health_score?: number | null; event_score?: number | null; rank_components?: Record<string, unknown> | null; rank_metric_source?: string | null; signal_context?: Record<string, unknown> | null; universe?: Record<string, unknown> | null; run_id: string; dataset_id: string; symbol: string; strategy_id: string; decision_date: string; trigger_date: string | null; confirmation_date: string | null; confirmation_status: string; signal_age_bars: number | null; expire_date: string | null; timeliness: string; primary_event: string; rank: number | null; rank_score: number | null; rank_formula: string | null; executable_date: string | null; execution_status: string; entry_policy: string; effective_entry_delay_bars: number; draft_eligible: boolean; excluded_reasons: string[]; events: string[]; risk_events: string[]; event_dates: Record<string, string>; quality_flags: string[] }
type Appearance = { symbol: string; dataset_id: string; overlap_count: number; signal_dates: string[]; strategies: Array<{ strategy_id: string; appearance_count: number; dates: string[]; scores: Array<{ date: string; value: number | null; run_id: string }> }>; range_performance: { status: string; start_date: string | null; end_date: string | null; start_close: string | null; end_close: string | null; return_pct: number | null; max_drawdown_pct: number | null; bar_count: number } }
type Report = { id: string; scan_id?: string; as_of_date?: string; created_at?: string; signal_count?: number; symbol_count?: number; request?: Record<string, unknown>; result?: { as_of_date: string; signal_count: number; rows: Row[]; per_symbol: Appearance[]; same_day_intersection: Array<{ symbol: string; decision_date: string }>; notes: string[]; source: { kind: string; is_subset?: boolean; selected_count?: number; available_count?: number }; version: string; code_sha256: string } }
const stateNames: Record<string, string> = { active: 'Active · 有效', expiring: 'Expiring · 临期', expired: '已过期', unknown: '未知' }
const confirmationNames: Record<string, string> = { confirmed: '已观察确认', confirmed_on_observation: '当次观察触发', pending: '待确认', partial: '部分确认', unconfirmed: '未确认', risk_blocked: '风险阻止', failed: '确认失败' }
const today = () => new Date().toLocaleDateString('sv-SE')
const pct = (value: number | null) => value === null ? '缺失' : `${value.toFixed(2)}%`
const parameterNames: Record<string, string> = { min_score: '综合分下限', min_event_count: '最少正向事件数', require_sequence: '要求事件链顺序', health_score_min: '健康分下限', event_score_min: '事件分下限', event_grade_min: '事件等级下限', require_key_event_confirmation: '要求关键事件确认', rank_weight_health: '排名权重：健康', rank_weight_event: '排名权重：事件', rank_weight_strength: '排名权重：强度', rank_weight_volume: '排名权重：量能', rank_weight_structure: '排名权重：结构' }
const paramStrings = (strategy?: Strategy) => Object.fromEntries(Object.entries(strategy?.signal_params || {}).map(([key, value]) => [key, String(value)]))
type ScanStrategy = { strategy_id: string; params: Record<string, string> }

export function SignalWorkspace({ onOpenMarket, onOpenResearch }: { onOpenMarket: (id: string) => void; onOpenResearch: (id: string) => void }) {
  const [datasets, setDatasets] = useState<Dataset[]>([]), [strategies, setStrategies] = useState<Strategy[]>([]), [scans, setScans] = useState<Scan[]>([])
  const [sources, setSources] = useState<Sources>({ trend_pools: [], tdx_jobs: [], notes: [] }), [reports, setReports] = useState<Report[]>([])
  const [sourceKind, setSourceKind] = useState('fixed'), [sourceId, setSourceId] = useState(''), [step, setStep] = useState('step4'), [sourcePreview, setSourcePreview] = useState<SourcePreview | null>(null)
  const [selected, setSelected] = useState<string[]>([]), [strategyId, setStrategyId] = useState(''), [params, setParams] = useState<Record<string, string>>({})
  const [contextMode, setContextMode] = useState('observation'), [candidatePath, setCandidatePath] = useState('legacy_store'), [eventWindow, setEventWindow] = useState('60')
  const [universeMode, setUniverseMode] = useState('strategy_filtered')
  const [profiles, setProfiles] = useState<EventProfileCatalog | null>(null), [profileId, setProfileId] = useState(''), [strategyBasket, setStrategyBasket] = useState<ScanStrategy[]>([])
  const [scanMode, setScanMode] = useState('single'), [scanFrom, setScanFrom] = useState(today), [scanTo, setScanTo] = useState(today), [strict, setStrict] = useState(true)
  const [scanPreview, setScanPreview] = useState<{ input_sha256: string; evaluation_count: number; source: SourcePreview } | null>(null), [jobId, setJobId] = useState('')
  const [scanId, setScanId] = useState(''), [asOf, setAsOf] = useState(today), [ageMin, setAgeMin] = useState('0'), [ageMax, setAgeMax] = useState(''), [delay, setDelay] = useState('1')
  const [timeliness, setTimeliness] = useState('all'), [market, setMarket] = useState(''), [board, setBoard] = useState(''), [overlap, setOverlap] = useState('1'), [minScore, setMinScore] = useState('')
  const [report, setReport] = useState<Report | null>(null), [reportPreview, setReportPreview] = useState<Report | null>(null), [showExcluded, setShowExcluded] = useState(false), [detail, setDetail] = useState<Row | null>(null)
  const [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState(''), [deleteId, setDeleteId] = useState(''), [page, setPage] = useState(0), [search, setSearch] = useState('')

  async function refresh() {
    const [d, s, h, p, r, ep] = await Promise.all([api<Dataset[]>('/market/datasets'), api<Strategy[]>('/research/strategies'), api<Scan[]>('/research/scans'), api<Sources>('/research/signal-workspace/sources'), api<Report[]>('/research/signal-workspace/reports'), api<EventProfileCatalog>('/research/event-profiles')])
    setDatasets(d); setStrategies(s); setScans(h); setSources(p); setReports(r); setProfiles(ep)
    if (!strategyId) { const initial = s.find(item => item.default_in_rebuild && item.enabled_in_rebuild !== false && item.signal_params !== null); if (initial) { setStrategyId(initial.id); setParams(Object.fromEntries(Object.entries(initial.signal_params || {}).map(([key, value]) => [key, String(value)]))) } }
  }
  useEffect(() => { void refresh().catch(err => setError(err instanceof Error ? err.message : '信号工作区读取失败')) }, [])
  useEffect(() => { setScanPreview(null) }, [sourceKind, sourceId, step, selected, strategyId, params, scanMode, scanFrom, scanTo, strict, contextMode, candidatePath, eventWindow, universeMode, profileId, profiles, strategyBasket])
  useEffect(() => { setReportPreview(null) }, [scanId, asOf, ageMin, ageMax, delay, timeliness, market, board, overlap, minScore])
  const scanStrategies = (contextMode === 'full' ? sources.signal_context_strategies || [] : strategies.filter(item => item.signal_params !== null)).filter(item => strategies.find(row => row.id === item.id)?.enabled_in_rebuild !== false)
  const currentStrategy = scanStrategies.find(item => item.id === strategyId)
  const currentProfile = profiles?.profiles.find(item => item.profile_id === (profileId || profiles.active_profile_id))
  const source: Source = { kind: sourceKind, ...(sourceKind === 'trend_pool' ? { screener_run_id: sourceId, step } : sourceKind === 'tdx' ? { tdx_job_id: sourceId } : {}), dataset_ids: selected }
  const scanBody = { source, scan: { strategies: strategyBasket.length ? strategyBasket : [{ strategy_id: strategyId, params }], strict, ...(contextMode === 'full' ? { signal_context: { candidate_path: candidatePath, window_days: Number(eventWindow), universe_mode: universeMode }, ...(currentProfile ? { event_profile_id: currentProfile.profile_id, event_profile_revision: currentProfile.revision } : {}) } : {}), ...(scanMode === 'single' ? { as_of_date: scanTo } : { date_from: scanFrom, date_to: scanTo }) } }
  const reportBody = { scan_id: scanId, as_of_date: asOf, signal_age_min: Number(ageMin), signal_age_max: ageMax === '' ? null : Number(ageMax), entry_delay_bars: Number(delay), timeliness, markets: market ? [market] : [], boards: board ? [board] : [], min_overlap: Number(overlap), min_rank_score: minScore === '' ? null : Number(minScore) }
  const shown = report || reportPreview
  const rows = (shown?.result?.rows || []).filter(row => showExcluded || row.excluded_reasons.length === 0)
  const available = sourceKind === 'fixed' ? datasets : datasets.filter(item => sourcePreview?.available_dataset_ids.includes(item.id))
  const visible = available.filter(item => item.symbol.toLowerCase().includes(search.trim().toLowerCase()))

  async function action(name: string, callback: () => Promise<void>) {
    setBusy(name); setError(''); setNotice('')
    try { await callback() } catch (err) { setError(err instanceof Error ? err.message : '操作失败') } finally { setBusy('') }
  }
  function chooseStrategy(id: string) {
    setStrategyId(id)
    setParams(strategyBasket.find(item => item.strategy_id === id)?.params || paramStrings(scanStrategies.find(item => item.id === id)))
  }
  function chooseContext(mode: string) {
    const choices = mode === 'full' ? sources.signal_context_strategies || [] : strategies.filter(item => item.signal_params !== null)
    const current = choices.find(item => item.id === strategyId && strategies.find(row => row.id === item.id)?.enabled_in_rebuild !== false)
    setContextMode(mode); setStrategyBasket([]); setStrategyId(current?.id || ''); setParams(paramStrings(current)); setScanPreview(null)
  }
  function chooseScan(id: string) {
    setScanId(id); const scan = scans.find(item => item.id === id)
    if (scan) setAsOf(scan.as_of_date || scan.date_to || today())
  }
  async function openScan(id: string) {
    await refresh(); setScanId(id)
    const scan = await api<Scan>(`/research/scans/${id}`)
    setAsOf(scan.as_of_date || scan.date_to || today()); setNotice('扫描已完成，可以预览信号报告。')
  }
  return <section className="panel"><div className="section-heading"><div><h2>信号工作区</h2><p className="muted">从保存的判断证据查看信号年龄、确认、排名与区间表现。历史状态固定在报告截至日。</p></div><button type="button" disabled={Boolean(busy)} onClick={() => action('refresh', refresh)}>刷新来源与历史</button></div>
    {error && <p className="danger" role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}
    <details><summary>从固定样本 / 趋势池 / 本地通达信集合启动扫描</summary><p className="muted">复用后台扫描队列。单次最多 100 个样本、单日 100 次或区间 1000 次判断。超出时请显式选子集；当前本地文件集合不代表已核验的历史全市场。</p>
      <div className="form-grid"><label className="field"><span>候选来源</span><select value={sourceKind} onChange={event => { setSourceKind(event.target.value); setSourceId(''); setSourcePreview(null); setSelected([]) }}><option value="fixed">固定行情样本</option><option value="trend_pool">已保存趋势筛选池</option><option value="tdx">已完成通达信任务</option></select></label>
      {sourceKind !== 'fixed' && <label className="field"><span>来源记录</span><select value={sourceId} onChange={event => { setSourceId(event.target.value); setSourcePreview(null); setSelected([]) }}><option value="">请选择</option>{(sourceKind === 'trend_pool' ? sources.trend_pools : sources.tdx_jobs).map(item => <option key={item.id} value={item.id}>{item.as_of_date} · {item.id.slice(0, 12)}</option>)}</select></label>}
      {sourceKind === 'trend_pool' && <label className="field"><span>筛选阶段</span><select value={step} onChange={event => { setStep(event.target.value); setSourcePreview(null); setSelected([]) }}>{['input', 'step1', 'step2', 'step3', 'step4'].map(value => <option key={value}>{value}</option>)}</select></label>}
      {sourceKind !== 'fixed' && <button type="button" disabled={Boolean(busy) || !sourceId} onClick={() => action('source', async () => { const next = await api<SourcePreview>('/research/signal-workspace/source-preview', 'POST', { ...source, dataset_ids: undefined }); setSourcePreview(next); setSelected([]) })}>读取候选集合</button>}
      <label className="field"><span>证券搜索</span><input value={search} onChange={event => setSearch(event.target.value)} /></label></div>
      <p>已选择 {selected.length} / 可选 {available.length} 个样本{sourcePreview && `；来源共有 ${sourcePreview.available_count} 个`}</p><div className="table-wrap" style={{ maxHeight: 220, overflow: 'auto' }}><table><thead><tr><th>选择</th><th>证券</th><th>范围</th><th>可得时间质量</th></tr></thead><tbody>{visible.map(item => <tr key={item.id}><td><input type="checkbox" aria-label={`选择信号样本 ${item.symbol}`} checked={selected.includes(item.id)} onChange={event => setSelected(current => event.target.checked ? [...current, item.id] : current.filter(id => id !== item.id))} /></td><td>{item.symbol}</td><td>{item.first_date} — {item.last_date}</td><td>{item.availability_quality}</td></tr>)}</tbody></table></div>
      <div className="form-grid"><label className="field"><span>信号计算口径</span><select value={contextMode} onChange={event => chooseContext(event.target.value)}><option value="observation">单股观察 · 原有运行器</option><option value="full">完整上下文 · 候选门槛与排名</option></select></label>
        {contextMode === 'full' && <><label className="field"><span>候选指标口径</span><select value={candidatePath} onChange={event => setCandidatePath(event.target.value)}><option value="legacy_store">旧行情仓口径</option><option value="legacy_tdx">旧通达信筛选口径</option></select></label><label className="field"><span>事件窗口（K线）</span><input type="number" min="20" max="240" step="1" value={eventWindow} onChange={event => setEventWindow(event.target.value)} /></label><label className="field"><span>扫描事件模板</span><select value={profileId} onChange={event => setProfileId(event.target.value)}><option value="">当前启用模板</option>{profiles?.profiles.map(item => <option key={item.profile_id} value={item.profile_id}>{item.name} · v{item.revision}</option>)}</select></label></>}
      </div>
      {contextMode === 'full' && <><label className="field"><span>候选预筛方式</span><select value={universeMode} onChange={event => setUniverseMode(event.target.value)}><option value="strategy_filtered">先执行策略候选预筛</option><option value="full_market">所选样本全部进入信号生成</option></select></label><p className="muted">候选门槛、事件证据和排名使用同一冻结截面。两种候选指标口径可能产生不同结果；当前冻结模板：{currentProfile ? `${currentProfile.name} · v${currentProfile.revision}` : '尚未读取'}。矩阵与 B1 使用各自规则，不共享统一分数。全部进入模式只跳过策略候选预筛，保留信号生成门槛；所选集合仍是固定样本，并非已核验的历史全市场。</p></>}
      <div className="form-grid"><label className="field"><span>信号策略</span><select value={strategyId} onChange={event => chooseStrategy(event.target.value)}><option value="">请选择</option>{scanStrategies.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field"><span>扫描模式</span><select value={scanMode} onChange={event => setScanMode(event.target.value)}><option value="single">单日</option><option value="range">区间</option></select></label>{scanMode === 'range' && <label className="field"><span>扫描开始日</span><input type="date" value={scanFrom} onChange={event => setScanFrom(event.target.value)} /></label>}<label className="field"><span>扫描截至日</span><input type="date" value={scanTo} onChange={event => setScanTo(event.target.value)} /></label><label className="field"><span>严格可得时间</span><input type="checkbox" checked={strict} onChange={event => setStrict(event.target.checked)} /></label></div>
      {currentStrategy && <details><summary>策略参数 · 冻结当前值</summary><div className="form-grid">{Object.entries(params).map(([key, value]) => { const spec = currentStrategy.params_schema[key]; const options = spec?.type === 'enum' ? spec.options || spec.enum : undefined; return <label className="field" key={key}><span>{parameterNames[key] || spec?.title || key}</span>{spec?.type === 'boolean' ? <select value={value} onChange={event => setParams(current => ({ ...current, [key]: event.target.value }))}><option value="true">启用</option><option value="false">关闭</option></select> : options ? <select value={value} onChange={event => setParams(current => ({ ...current, [key]: event.target.value }))}>{options.map(option => <option key={option}>{option}</option>)}</select> : <input type="number" min={spec?.minimum} max={spec?.maximum} step={spec?.type === 'integer' ? 1 : 'any'} value={value} onChange={event => setParams(current => ({ ...current, [key]: event.target.value }))} />}</label> })}</div></details>}
      <div className="button-row"><button type="button" disabled={!currentStrategy || (strategyBasket.length >= 10 && !strategyBasket.some(item => item.strategy_id === strategyId))} onClick={() => { setStrategyBasket(current => [...current.filter(item => item.strategy_id !== strategyId), { strategy_id: strategyId, params: { ...params } }]); setNotice('已保存该策略当前参数到本次组合。继续编辑后须再次更新组合。') }}>{strategyBasket.some(item => item.strategy_id === strategyId) ? '更新组合中此策略参数' : '加入多策略组合'}</button>{strategyBasket.length > 0 && <button type="button" onClick={() => setStrategyBasket([])}>清空组合，使用当前单策略</button>}</div>
      {strategyBasket.length > 0 && <><p className="muted">本次扫描使用以下 {strategyBasket.length} 个策略及各自已保存参数（最多 10 个），用于区间共振与交叉验证。编辑表单后须点击更新。</p><ul>{strategyBasket.map(item => <li key={item.strategy_id}>{strategies.find(row => row.id === item.strategy_id)?.name || item.strategy_id} · {Object.keys(item.params).length} 项参数 <button type="button" className="link-button" onClick={() => chooseStrategy(item.strategy_id)}>查看已保存参数</button> <button type="button" className="link-button" onClick={() => setStrategyBasket(current => current.filter(row => row.strategy_id !== item.strategy_id))}>移出本次组合</button></li>)}</ul></>}
      <div className="button-row"><button disabled={Boolean(busy) || (!currentStrategy && !strategyBasket.length) || !selected.length || selected.length > 100 || (contextMode === 'full' && (!currentProfile || !Number.isInteger(Number(eventWindow)) || Number(eventWindow) < 20 || Number(eventWindow) > 240))} onClick={() => action('scan-preview', async () => setScanPreview(await api('/research/signal-workspace/scan-preview', 'POST', scanBody)))}>预览冻结扫描</button>{scanPreview && <><span>{scanPreview.evaluation_count} 次判断 · {scanPreview.source.is_subset ? '来源子集' : '所选完整集合'}</span><button className="primary-button" disabled={Boolean(busy)} onClick={() => action('scan', async () => { const job = await api<{ id: string }>('/research/signal-workspace/scan-jobs', 'POST', { ...scanBody, expected_preview_sha256: scanPreview.input_sha256 }); setJobId(job.id); setScanPreview(null); setNotice('已进入共享计算队列。') })}>确认启动后台扫描</button></>}</div>
    </details>
    <ScanJobs focusId={jobId} onOpen={id => void action('open-scan', () => openScan(id))} />
    <h3>报告范围与过滤</h3><p className="muted">多策略共振选择现有多策略扫描；区间共振统计整个区间各策略的出现，另列同日交集。分数只在同一策略内比较。</p>
    <div className="form-grid"><label className="field"><span>已完成扫描</span><select value={scanId} onChange={event => chooseScan(event.target.value)}><option value="">请选择扫描记录</option>{scans.map(item => <option key={item.id} value={item.id}>{item.as_of_date || `${item.date_from} 至 ${item.date_to}`} · {item.signal_count} 次信号 · {item.id.slice(0, 8)}</option>)}</select></label><label className="field"><span>报告截至日</span><input type="date" value={asOf} onChange={event => setAsOf(event.target.value)} /></label><label className="field"><span>最小信号年龄（交易 K 线）</span><input type="number" min="0" max="2000" value={ageMin} onChange={event => setAgeMin(event.target.value)} /></label><label className="field"><span>最大信号年龄（留空不限）</span><input type="number" min="0" max="2000" value={ageMax} onChange={event => setAgeMax(event.target.value)} /></label><label className="field"><span>确认后延迟入场 K 线</span><input type="number" min="1" max="5" value={delay} onChange={event => setDelay(event.target.value)} /></label><label className="field"><span>时效</span><select value={timeliness} onChange={event => setTimeliness(event.target.value)}><option value="all">全部</option>{['active', 'expiring', 'expired'].map(value => <option key={value} value={value}>{stateNames[value]}</option>)}</select></label><label className="field"><span>交易所</span><select value={market} onChange={event => setMarket(event.target.value)}><option value="">全部</option><option value="sh">上海</option><option value="sz">深圳</option><option value="bj">北京</option></select></label><label className="field"><span>板块</span><select value={board} onChange={event => setBoard(event.target.value)}><option value="">全部</option><option value="main">主板</option><option value="star">科创板</option><option value="chinext">创业板</option><option value="beijing">北交所</option></select></label><label className="field"><span>区间最少共振策略数</span><input type="number" min="1" max="10" value={overlap} onChange={event => setOverlap(event.target.value)} /></label><label className="field"><span>同策略排名分下限</span><input type="number" min="0" max="100" value={minScore} onChange={event => setMinScore(event.target.value)} /></label></div>
    <div className="button-row"><button type="button" disabled={Boolean(busy) || !scanId} onClick={() => action('preview', async () => { const next = await api<Report>('/research/signal-workspace/preview', 'POST', reportBody); setReport(null); setReportPreview(next); setDetail(null); setPage(0) })}>预览信号报告</button>{reportPreview && <button type="button" className="primary-button" disabled={Boolean(busy)} onClick={() => action('save', async () => { const next = await api<Report>('/research/signal-workspace/reports', 'POST', { ...reportBody, expected_preview_sha256: reportPreview.id }); setReport(next); setReportPreview(null); await refresh(); setNotice('已保存不可变信号报告。') })}>保存这份报告</button>}</div>
    {shown?.result && <><h3>{report ? '已保存报告' : '报告预览'} · 截至 {shown.result.as_of_date}</h3>{report && <p><a href={`/api/v1/research/signal-workspace/reports/${report.id}/cross-validation.csv`} download>导出交叉验证 CSV</a><small className="muted"> · 使用这份报告保存时的过滤条件；表单未保存的改动不影响导出。</small></p>}<p>{shown.result.signal_count} 条通过过滤的信号 · {shown.result.per_symbol.length} 只证券 · {shown.result.same_day_intersection.length} 次同日交集</p><p className="muted">{shown.result.notes.join('；')}</p><label><input type="checkbox" checked={showExcluded} onChange={event => { setShowExcluded(event.target.checked); setPage(0) }} /> 显示未通过过滤的原始证据</label>
      <div className="table-wrap"><table><thead><tr><th>证券 / 策略</th><th>发生 / 观察确认</th><th>年龄 / 时效</th><th>同策略排名</th><th>延迟入场观察</th><th>证据</th></tr></thead><tbody>{rows.slice(page * 50, page * 50 + 50).map(row => <tr key={row.run_id}><td>{row.symbol}<br /><small>{strategies.find(item => item.id === row.strategy_id)?.name || row.strategy_id}</small></td><td>{row.trigger_date || '未知'}<br />{row.confirmation_date || '未确认'} · {confirmationNames[row.confirmation_status] || row.confirmation_status}</td><td>{row.signal_age_bars ?? '未知'} 根<br />{stateNames[row.timeliness] || row.timeliness}</td><td>{row.rank === null ? '无完整排名能力' : `#${row.rank} · ${row.rank_score?.toFixed(2)}`}</td><td>T+{row.effective_entry_delay_bars}<br />{row.executable_date || (row.execution_status === 'pending_future_bar' ? '等待后续行情' : '未满足条件')}</td><td><button type="button" className="link-button" onClick={() => setDetail(row)}>查看信号证据</button><button type="button" className="link-button" onClick={() => onOpenMarket(row.dataset_id)}>打开行情</button><button type="button" className="link-button" onClick={() => onOpenResearch(row.run_id)}>{row.draft_eligible ? '原研究 / 待买草稿' : '打开原研究'}</button>{row.excluded_reasons.length > 0 && <small className="muted">{row.excluded_reasons.join(' / ')}</small>}</td></tr>)}</tbody></table></div>{!rows.length && <p className="muted">没有通过当前过滤的信号，原判断仍保留。</p>}<div className="button-row"><button disabled={page === 0} onClick={() => setPage(value => value - 1)}>上一页</button><span>{page + 1} / {Math.max(1, Math.ceil(rows.length / 50))}</span><button disabled={(page + 1) * 50 >= rows.length} onClick={() => setPage(value => value + 1)}>下一页</button></div>
      {detail && <details open><summary>信号证据 · {detail.symbol} · {detail.primary_event}</summary><p>源研究 {detail.run_id}；决策日 {detail.decision_date}；到期日 {detail.expire_date || '未知'}。确认日为保存观察的上界，不是事件回标日。</p><p>正向事件：{detail.events.join(' / ') || '无'}；风险事件：{detail.risk_events.join(' / ') || '无'}；排名公式：{detail.rank_formula || '能力未提供'}。</p><p>健康分：{detail.health_score ?? '未提供'}；事件分：{detail.event_score ?? '未提供'}；排名来源：{detail.rank_metric_source || '未提供'}。</p>{detail.signal_context && <p style={{ overflowWrap: 'anywhere' }}>冻结上下文：{JSON.stringify(detail.signal_context)}</p>}{detail.rank_components && <div className="table-wrap"><table><thead><tr><th>排名分项</th><th>保存值</th></tr></thead><tbody>{Object.entries(detail.rank_components).map(([key, value]) => <tr key={key}><td>{parameterNames[key] || key}</td><td>{value == null ? '未提供' : typeof value === 'object' ? JSON.stringify(value) : String(value)}</td></tr>)}</tbody></table></div>}{detail.universe && <details><summary>候选门槛证据</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify(detail.universe, null, 2)}</pre></details>}<p>入场规则：{detail.entry_policy === 'legacy_fixed_t1' ? '旧涨停套利插件固定 T+1' : '确认与决策之后的已观察交易 K 线'}。{detail.quality_flags.join(' / ')}</p><div className="table-wrap"><table><thead><tr><th>事件</th><th>发生日</th></tr></thead><tbody>{Object.entries(detail.event_dates).map(([key, value]) => <tr key={key}><td>{key}</td><td>{value}</td></tr>)}</tbody></table></div></details>}
      <h3>区间共振与价格表现</h3><p className="muted">首末有效收盘、不含费用；区间价格变化与回撤不代表实际组合交易收益。无价格显示缺失。</p><div className="table-wrap"><table><thead><tr><th>证券 / 策略次数</th><th>出现日期</th><th>有效价格端点</th><th>区间价格变化</th><th>最大收盘回撤</th></tr></thead><tbody>{shown.result.per_symbol.map(item => <tr key={item.symbol}><td>{item.symbol} · {item.overlap_count} 策略{item.strategies.map(strategy => <details key={strategy.strategy_id}><summary>{strategy.strategy_id} · {strategy.appearance_count} 次</summary><p>{strategy.dates.join(' / ')}</p><ul>{strategy.scores.map(score => <li key={score.run_id}>{score.date} · {score.value?.toFixed(2) ?? '无排名分'} <button type="button" className="link-button" onClick={() => onOpenResearch(score.run_id)}>原研究</button></li>)}</ul></details>)}</td><td>{item.signal_dates.join(' / ')}</td><td>{item.range_performance.start_date || '缺失'} ({item.range_performance.start_close || '—'})<br />{item.range_performance.end_date || '缺失'} ({item.range_performance.end_close || '—'}) · {item.range_performance.bar_count} 根</td><td>{pct(item.range_performance.return_pct)}</td><td>{pct(item.range_performance.max_drawdown_pct)}</td></tr>)}</tbody></table></div><details><summary>冻结版本与来源</summary><p style={{ overflowWrap: 'anywhere' }}>{shown.result.version} · {shown.result.code_sha256}</p><p>来源 {shown.result.source.kind}；{shown.result.source.is_subset ? '已明确选择子集' : '冻结样本集合'}；历史成员覆盖未经核验。</p></details></>}
    <h3>信号报告历史</h3><div className="table-wrap"><table><thead><tr><th>截至日</th><th>信号 / 证券</th><th>保存时间</th><th>操作</th></tr></thead><tbody>{reports.map(item => <tr key={item.id}><td>{item.as_of_date}</td><td>{item.signal_count} / {item.symbol_count}</td><td>{item.created_at?.slice(0, 19)}</td><td><button type="button" className="link-button" disabled={Boolean(busy)} onClick={() => action('history', async () => { setReport(await api(`/research/signal-workspace/reports/${item.id}`)); setReportPreview(null); setDetail(null); setPage(0) })}>查看信号报告</button><button type="button" className="link-button danger" onClick={() => setDeleteId(item.id)}>删除报告</button></td></tr>)}</tbody></table></div>{deleteId && <div role="alert"><p>仅删除这份信号报告，原扫描和研究证据保留。</p><button type="button" disabled={Boolean(busy)} onClick={() => action('delete', async () => { await api(`/research/signal-workspace/reports/${deleteId}`, 'DELETE'); if (report?.id === deleteId) setReport(null); setDeleteId(''); await refresh() })}>确认删除报告</button><button type="button" onClick={() => setDeleteId('')}>取消</button></div>}
  </section>
}
