import { useEffect, useMemo, useRef, useState } from 'react'
import { api } from './api'
import { useTaskDeepLink } from './task-deep-link'

type Axis = { key: string; values: string; min: string; max: string; precision: number }
type Metrics = { total_return: number; max_drawdown: number; trade_count: number; win_rate: number | null }
type Selection = { selected_candidate_sha256: string | null; reason: string | null; ranking: Array<{ candidate_sha256: string; train_task_id: string; point_score: number; plateau_score: number | null; metrics: Metrics }>; rejected: Array<{ candidate_sha256: string; reason: string }> }
type Fold = { index: number; train_start: string; train_end: string; test_start: string; test_end: string; state?: string; selection?: Selection | null; selection_sha256?: string | null }
type Task = { id: string; fold_index: number; role: string; ordinal: number; candidate_sha256: string | null; state: string; error: string | null; attempt_number: number; axis_values: Record<string, string> | null; metrics: Metrics | null; params: Record<string, unknown> | null; config: Record<string, unknown> | null; result?: Record<string, unknown> | null }
type Plan = { sampling: { seed: number; sampling_mode: string; actual_points: number; requested_points: number; deduplicated_points: number }; temporal: { folds: Fold[]; actual_folds: number; evaluation_points: number; unused_tail_bars: number; min_train_trades: number; notes: string[] } }
type Job = { id: string; name: string; strategy_id: string; state: string; error: string | null; plan: Plan; counts: Record<string, number>; elapsed_ms: number; capabilities: Record<string, boolean>; folds?: Fold[]; tasks?: Task[]; frozen_context?: Record<string, unknown>; analysis?: { oos_normalized_curve: Array<{ date: string; normalized_assets: number; fold_index: number }>; oos_compounded_return: number | null; oos_max_drawdown: number | null; oos_trade_count: number; completed_test_folds: number; planned_folds: number; positive_test_fold_rate: number | null; limitations: string[]; quality_flags: string[] } | null }
type Preview = { key: string; preview_sha256: string; plan: Plan; candidates: Array<{ ordinal: number; axis_values: Record<string, string>; error: string | null }> }
type Source = { id: string; strategy_id: string; state: string; created_at: string }
type Spec = { type: string; minimum?: number; maximum?: number }
const pct = (value: number | null | undefined) => value == null ? '—' : `${(value * 100).toFixed(2)}%`
const labels: Record<string, string> = { queued: '排队', running: '执行中', pausing: '正在暂停，等待检查点', paused: '已暂停', cancelling: '正在取消', cancelled: '已取消', succeeded: '已完成', failed: '失败', invalid: '无效候选', blocked: '等待训练选择', skipped: '已跳过', waiting_train: '等待训练', training: '训练中', waiting_test: '选择已冻结，等待测试', testing: '测试中', completed: '测试完成' }

function FoldPlan({ folds }: { folds: Fold[] }) { return <div className="table-wrap"><table aria-label="滚动时间折计划"><thead><tr><th>折</th><th>训练区间</th><th>后续测试区间</th></tr></thead><tbody>{folds.map(fold => <tr key={fold.index}><td>{fold.index + 1}</td><td>{fold.train_start} → {fold.train_end}</td><td>{fold.test_start} → {fold.test_end}</td></tr>)}</tbody></table></div> }

export function WalkForwardWorkspace({ baseRunId }: { baseRunId?: string }) {
  const [sourceId, setSourceId] = useState(baseRunId || '')
  const [sources, setSources] = useState<Source[]>([])
  const [schema, setSchema] = useState<Record<string, Spec>>({})
  const [name, setName] = useState('滚动验证实验')
  const [mode, setMode] = useState<'grid' | 'lhs'>('grid')
  const [seed, setSeed] = useState('20260926')
  const [samples, setSamples] = useState(12)
  const [maxPoints, setMaxPoints] = useState(40)
  const [axes, setAxes] = useState<Axis[]>([{ key: 'config.holding_bars', values: '3,5,10', min: '2', max: '20', precision: 0 }])
  const [window, setWindow] = useState({ initial_train_bars: 120, test_bars: 40, warmup_bars: 0, gap_bars: 1, max_folds: 4, min_train_trades: 3 })
  const [preview, setPreview] = useState<Preview | null>(null)
  const [jobs, setJobs] = useState<Job[]>([])
  const [selected, setSelected] = useState<Job | null>(null)
  const [task, setTask] = useState<Task | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [deleteId, setDeleteId] = useState('')
  const live = useRef(true)
  const selectedId = useRef('')
  const taskRequest = useRef(0)
  useEffect(() => { live.current = true; return () => { live.current = false } }, [])
  useEffect(() => { if (baseRunId) setSourceId(baseRunId) }, [baseRunId])
  async function refresh() { const [runs, backtests] = await Promise.all([api<Job[]>('/research/walk-forwards'), api<Source[]>('/backtests')]); if (live.current) { setJobs(runs); setSources(backtests.filter(item => item.state === 'succeeded')) } }
  useEffect(() => { refresh().catch(err => { if (live.current) setError(err.message) }) }, [])
  useEffect(() => { let current = true; setSchema({}); if (sourceId) api<{ schema: Record<string, Spec> }>(`/research/plateaus/schema/${sourceId}`).then(value => { if (current) setSchema(value.schema) }).catch(err => { if (current) setError(err.message) }); return () => { current = false } }, [sourceId])
  const active = jobs.some(job => ['queued', 'running', 'pausing', 'cancelling'].includes(job.state))
  useEffect(() => { if (!active) return; let pending = false; const timer = setInterval(async () => { if (pending) return; pending = true; try { await refresh(); const id = selectedId.current; if (id) { const job = await api<Job>(`/research/walk-forwards/${id}`); if (live.current && selectedId.current === id) setSelected(job) } } catch (err) { if (live.current) setError(err instanceof Error ? err.message : String(err)) } finally { pending = false } }, 2000); return () => clearInterval(timer) }, [active])
  const body = useMemo(() => ({ base_run_id: sourceId, sampling_mode: mode, seed: seed.trim() ? Number(seed) : null, sample_points: samples, max_points: maxPoints, ...window,
    axes: Object.fromEntries(axes.map(axis => [axis.key, mode === 'grid' ? { values: axis.values.split(/[,，]/).map(value => value.trim()).filter(Boolean) } : { min: axis.min, max: axis.max, precision: axis.precision }])) }), [sourceId, mode, seed, samples, maxPoints, window, axes])
  const previewKey = JSON.stringify(body), checked = preview?.key === previewKey ? preview : null
  async function perform(action: () => Promise<void>) { setBusy(true); setError(''); setNotice(''); try { await action() } catch (err) { if (live.current) setError(err instanceof Error ? err.message : String(err)) } finally { if (live.current) setBusy(false) } }
  async function choose(id: string) { selectedId.current = id; setTask(null); setDeleteId(''); const job = await api<Job>(`/research/walk-forwards/${id}`); if (live.current && selectedId.current === id) setSelected(job) }
  useTaskDeepLink('walk_forward', choose, '[aria-label="滚动验证详情"]', setError)
  async function chooseTask(id: string) { const jobId = selectedId.current, token = ++taskRequest.current; const value = await api<Task>(`/research/walk-forwards/${jobId}/tasks/${id}`); if (live.current && selectedId.current === jobId && token === taskRequest.current) setTask(value) }
  async function control(id: string, action: string) { await api(`/research/walk-forwards/${id}${action === 'delete' ? '' : '/' + action}`, action === 'delete' ? 'DELETE' : 'POST', {}); if (action === 'delete') { if (selectedId.current === id) { selectedId.current = ''; setSelected(null); setTask(null) } setDeleteId('') } else await choose(id); await refresh() }
  function changeAxis(index: number, patch: Partial<Axis>) { setAxes(rows => rows.map((axis, at) => at === index ? { ...axis, ...patch } : axis)) }
  const curve = selected?.analysis?.oos_normalized_curve || []
  const low = Math.min(1, ...curve.map(point => point.normalized_assets)), high = Math.max(1, ...curve.map(point => point.normalized_assets))
  const path = curve.map((point, index) => `${index ? 'L' : 'M'} ${index / Math.max(1, curve.length - 1) * 760} ${155 - (point.normalized_assets - low) / Math.max(.0001, high - low) * 145}`).join(' ')
  return <section className="card" aria-label="滚动样本外验证" style={{ marginTop: 20 }}>
    <div className="section-header"><div><h3>滚动样本外验证 · Walk-forward</h3><p className="muted">按时间先训练、冻结参数选择、再测试。使用新建的 grid / LHS 候选计划，最多 400 个训练与测试点，共享单个计算进程。</p></div><button type="button" className="button secondary" disabled={busy} onClick={() => perform(refresh)}>刷新滚动验证历史</button></div>
    <p className="muted">来源回测提供行情、基础参数和事件模板。当前支持单股扩展训练，每折测试清空仓位并重置资金；手工候选设计是否看过历史后段，系统无法证明。已发布的训练选择不能在看过测试结果后被重试改写。</p>
    {error && <p className="alert error" role="alert">{error}</p>}{notice && <p className="alert" role="status">{notice}</p>}
    <div className="form-grid"><label><span>滚动实验名称</span><input value={name} onChange={event => setName(event.target.value)} maxLength={80} /></label>
      <label><span>滚动验证来源回测</span><select value={sourceId} onChange={event => setSourceId(event.target.value)}><option value="">选择已完成回测</option>{sources.map(source => <option key={source.id} value={source.id}>{source.strategy_id} · {source.created_at.slice(0, 19)} · {source.id.slice(0, 8)}</option>)}</select></label>
      <label><span>候选采样方式</span><select value={mode} onChange={event => setMode(event.target.value as 'grid' | 'lhs')}><option value="grid">grid 完整网格</option><option value="lhs">LHS 分层采样</option></select></label>
      <label><span>候选随机种子</span><input value={seed} onChange={event => setSeed(event.target.value)} placeholder="留空由预览生成" /></label>
      <label><span>每折候选点上限</span><input type="number" min={1} max={399} value={maxPoints} onChange={event => setMaxPoints(Number(event.target.value))} /></label>
      {mode === 'lhs' && <label><span>LHS 候选点数</span><input type="number" min={1} max={399} value={samples} onChange={event => setSamples(Number(event.target.value))} /></label>}
      {([['initial_train_bars', '首次训练 K 线数'], ['test_bars', '每折测试 K 线数'], ['warmup_bars', '初始预热 K 线数'], ['gap_bars', '训练测试间隔 K 线数'], ['max_folds', '最多滚动折数'], ['min_train_trades', '训练最少完整交易数']] as const).map(([key, label]) => <label key={key}><span>{label}</span><input type="number" min={0} value={window[key]} onChange={event => setWindow({ ...window, [key]: Number(event.target.value) })} /></label>)}
    </div>
    {axes.map((axis, index) => <div className="toolbar" key={index} style={{ marginTop: 12, flexWrap: 'wrap' }}><label>候选维度 {index + 1}<select aria-label={`滚动候选维度 ${index + 1}`} value={axis.key} onChange={event => changeAxis(index, { key: event.target.value, precision: schema[event.target.value]?.type === 'integer' ? 0 : 4 })}>{Object.entries(schema).filter(([key, spec]) => !axes.some((item, at) => item.key === key && at !== index) && (mode === 'grid' || ['integer', 'number'].includes(spec.type))).map(([key]) => <option key={key}>{key}</option>)}</select></label>
      {mode === 'grid' ? <label>候选值，逗号分隔<input aria-label={`滚动网格取值 ${index + 1}`} value={axis.values} onChange={event => changeAxis(index, { values: event.target.value })} /></label> : <><label>下限<input aria-label={`滚动采样下限 ${index + 1}`} value={axis.min} onChange={event => changeAxis(index, { min: event.target.value })} /></label><label>上限<input aria-label={`滚动采样上限 ${index + 1}`} value={axis.max} onChange={event => changeAxis(index, { max: event.target.value })} /></label><label>小数精度<input type="number" min={0} max={6} aria-label={`滚动采样精度 ${index + 1}`} value={axis.precision} onChange={event => changeAxis(index, { precision: Number(event.target.value) })} /></label></>}
      <button type="button" className="button secondary" disabled={axes.length === 1 || busy} onClick={() => setAxes(axes.filter((_, at) => at !== index))}>移除候选维度 {index + 1}</button></div>)}
    <div className="toolbar" style={{ marginTop: 12 }}><button type="button" className="button secondary" disabled={busy || axes.length >= 8} onClick={() => { const key = Object.keys(schema).find(key => !axes.some(axis => axis.key === key) && (mode === 'grid' || ['integer', 'number'].includes(schema[key].type))); if (key) setAxes([...axes, { key, values: schema[key].type === 'boolean' ? 'true,false' : String(schema[key].minimum ?? 0), min: String(schema[key].minimum ?? 0), max: String(schema[key].maximum ?? 1), precision: schema[key].type === 'integer' ? 0 : 4 }]) }}>增加滚动候选维度</button>
      <button type="button" className="button secondary" disabled={busy || !sourceId || !Object.keys(schema).length} onClick={() => perform(async () => { const value = await api<Omit<Preview, 'key'>>('/research/walk-forwards/preview', 'POST', body); if (live.current) setPreview({ ...value, key: previewKey }) })}>预览候选与时间折</button></div>
    {checked && <section className="alert" aria-label="滚动验证计划预览" style={{ marginTop: 12 }}><p>冻结 {checked.plan.sampling.actual_points} 个候选 · {checked.plan.temporal.actual_folds} 折 · 共 {checked.plan.temporal.evaluation_points} 个计算点 · 种子 {checked.plan.sampling.seed} · 未测试尾部 {checked.plan.temporal.unused_tail_bars} 根。</p><FoldPlan folds={checked.plan.temporal.folds} /><p>{checked.plan.temporal.notes.join('；')}</p>
      <details><summary>查看训练候选组合</summary><pre style={{ whiteSpace: 'pre-wrap' }}>{JSON.stringify(checked.candidates.map(candidate => ({ point: candidate.ordinal + 1, params: candidate.axis_values, error: candidate.error })), null, 2)}</pre></details>
      <button type="button" className="button" disabled={busy || !name.trim()} onClick={() => perform(async () => { const job = await api<Job>('/research/walk-forwards', 'POST', { ...body, seed: checked.plan.sampling.seed, name, expected_preview_sha256: checked.preview_sha256 }); selectedId.current = job.id; setSelected(job); setTask(null); setNotice('滚动验证已排队；训练选参完成后才解锁对应测试任务。'); await refresh() })}>确认并创建滚动验证</button>
    </section>}
    <div className="table-wrap" style={{ marginTop: 20 }}><table aria-label="滚动验证历史"><thead><tr><th>实验</th><th>状态</th><th>折 / 检查点</th><th>操作</th></tr></thead><tbody>{jobs.map(job => <tr key={job.id}><td>{job.name}</td><td>{labels[job.state] || job.state}</td><td>{job.plan.temporal.actual_folds} 折 · {job.counts.succeeded || 0} 成功 / {job.counts.failed || 0} 失败 / {job.counts.skipped || 0} 跳过</td><td><button type="button" className="link-button" disabled={busy} onClick={() => perform(() => choose(job.id))}>查看滚动验证</button>{[['pause', '暂停滚动验证'], ['resume', '继续滚动验证'], ['cancel', '取消滚动验证'], ['retry', '重试未完成验证']] .map(([action, label]) => job.capabilities[action] && <button key={action} type="button" className="link-button" disabled={busy} onClick={() => perform(() => control(job.id, action))}>{label}</button>)}{job.capabilities.delete && <button type="button" className="link-button danger" disabled={busy} onClick={() => setDeleteId(job.id)}>删除滚动验证</button>}</td></tr>)}</tbody></table></div>
    {!jobs.length && <p className="muted">暂无滚动验证记录。</p>}
    {deleteId && <div className="alert error"><p>删除“{jobs.find(job => job.id === deleteId)?.name}”的历史入口？计算和训练选择检查点仍保留在审计数据中。</p><button type="button" className="button secondary danger" disabled={busy} onClick={() => perform(() => control(deleteId, 'delete'))}>确认删除滚动验证</button><button type="button" className="button secondary" onClick={() => setDeleteId('')}>保留滚动验证</button></div>}
    {selected && <section aria-label="滚动验证详情" style={{ marginTop: 24 }}><h3>{selected.name} · {labels[selected.state] || selected.state}</h3><p className="muted">{selected.strategy_id} · 累计 {(selected.elapsed_ms / 1000).toFixed(1)} 秒</p>{selected.error && <p className="alert error">{selected.error}</p>}<a className="button secondary" href={`/api/v1/research/walk-forwards/${selected.id}/export.json`} download>导出滚动验证 JSON</a>
      <FoldPlan folds={selected.folds || []} />
      {selected.folds?.map(fold => { const test = selected.tasks?.find(task => task.fold_index === fold.index && task.role === 'test'); return <section key={fold.index} style={{ marginTop: 16 }}><h4>第 {fold.index + 1} 折 · {labels[fold.state || ''] || fold.state}</h4><p>测试收益 {pct(test?.metrics?.total_return)} · 回撤 {pct(test?.metrics?.max_drawdown)} · 完整交易 {test?.metrics?.trade_count ?? '—'}</p>{fold.selection ? <><p className="muted">选择检查点 {fold.selection_sha256?.slice(0, 16)} · {fold.selection.selected_candidate_sha256 ? `候选 ${fold.selection.selected_candidate_sha256.slice(0, 16)}` : fold.selection.reason}</p><details><summary>第 {fold.index + 1} 折训练候选排名</summary><div className="table-wrap"><table><thead><tr><th>候选</th><th>训练收益</th><th>训练交易</th><th>训练评分</th><th>证据</th></tr></thead><tbody>{fold.selection.ranking.map(candidate => <tr key={candidate.candidate_sha256}><td>{candidate.candidate_sha256.slice(0, 12)}{candidate.candidate_sha256 === fold.selection?.selected_candidate_sha256 ? ' · 已选定' : ''}</td><td>{pct(candidate.metrics.total_return)}</td><td>{candidate.metrics.trade_count}</td><td>{(candidate.plateau_score ?? candidate.point_score).toFixed(2)}</td><td><button type="button" className="link-button" disabled={busy} onClick={() => perform(() => chooseTask(candidate.train_task_id))}>查看训练点</button></td></tr>)}</tbody></table></div>{fold.selection.rejected.map(candidate => <p className="muted" key={candidate.candidate_sha256}>{candidate.candidate_sha256.slice(0, 12)}：{candidate.reason}</p>)}</details></> : <p className="muted">候选训练尚未全部完成；测试任务保持锁定。</p>}{test && <button type="button" className="button secondary" disabled={busy} onClick={() => perform(() => chooseTask(test.id))}>查看第 {fold.index + 1} 折测试点</button>}</section> })}
      {selected.analysis && <section aria-label="样本外验证汇总"><h4>样本外结果 · 按折归一化拼接</h4><div className="period-summary"><span>完成测试 {selected.analysis.completed_test_folds}/{selected.analysis.planned_folds} 折</span><span>拼接收益 {pct(selected.analysis.oos_compounded_return)}</span><span>拼接回撤 {pct(selected.analysis.oos_max_drawdown)}</span><span>完整交易 {selected.analysis.oos_trade_count}</span><span>正收益折占比 {pct(selected.analysis.positive_test_fold_rate)}</span></div>
        {!!curve.length && <div className="backtest-chart"><svg viewBox="0 0 760 165" role="img" aria-label="按折归一化样本外曲线"><path d={path} fill="none" stroke="var(--chart-series1)" strokeWidth="2.5" /></svg><div className="period-summary"><span>{curve[0].date}</span><span>{curve.at(-1)?.date}</span></div></div>}
        <p className="muted">{selected.analysis.limitations.join('；')}</p><p className="muted">质量标记：{selected.analysis.quality_flags.join('、') || '无额外标记'}</p></section>}
      <details><summary>全部计算点与失败原因</summary><div className="table-wrap"><table><thead><tr><th>折 / 阶段</th><th>候选参数</th><th>状态 / 尝试</th><th>错误</th><th /></tr></thead><tbody>{selected.tasks?.map(item => <tr key={item.id}><td>{item.fold_index + 1} / {item.role === 'train' ? '训练' : '测试'}</td><td>{JSON.stringify(item.axis_values)}</td><td>{labels[item.state] || item.state} / {item.attempt_number}</td><td>{item.error || '—'}</td><td><button type="button" className="link-button" disabled={busy} onClick={() => perform(() => chooseTask(item.id))}>查看计算点</button></td></tr>)}</tbody></table></div></details>
      <details><summary>冻结行情版本与基础执行配置</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify(selected.frozen_context, null, 2)}</pre></details>
    </section>}
    {task && <section aria-label="滚动验证计算点" style={{ marginTop: 20 }}><h4>第 {task.fold_index + 1} 折 · {task.role === 'train' ? '训练点' : '测试点'} · {labels[task.state] || task.state}</h4><p>{task.error}</p><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{JSON.stringify({ params: task.params, config: task.config, metrics: task.metrics }, null, 2)}</pre>{task.result && <details><summary>冻结交易、权益曲线与决策证据</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', maxHeight: 400, overflow: 'auto' }}>{JSON.stringify(task.result, null, 2)}</pre></details>}</section>}
  </section>
}
