"""Generate deterministic OpenAPI and TypeScript contracts without starting Trade."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
METHODS = ('get', 'post', 'put', 'patch', 'delete', 'head', 'options')


def literal(value):
    return json.dumps(value, ensure_ascii=False, allow_nan=False)


def ts(schema):
    if schema is True or schema == {}: return 'unknown'
    if schema is False: return 'never'
    if '$ref' in schema:
        return 'Components[' + literal(schema['$ref'].rsplit('/', 1)[1]) + ']'
    if 'const' in schema: return literal(schema['const'])
    if 'enum' in schema: return '(' + ' | '.join(literal(value) for value in schema['enum']) + ')'
    for key, joiner in (('anyOf', ' | '), ('oneOf', ' | '), ('allOf', ' & ')):
        if key in schema: return '(' + joiner.join(ts(item) for item in schema[key]) + ')'
    kind = schema.get('type')
    if isinstance(kind, list): return '(' + ' | '.join(ts({**schema, 'type': item}) for item in kind) + ')'
    if kind == 'null': return 'null'
    if kind in ('integer', 'number'): return 'number'
    if kind == 'boolean': return 'boolean'
    if kind == 'string': return 'Blob' if schema.get('format') == 'binary' else 'string'
    if kind == 'array': return 'Array<' + ts(schema.get('items', {})) + '>'
    if kind == 'object' or 'properties' in schema:
        fields = schema.get('properties', {})
        required = schema.get('required', [])
        members = [literal(name) + ('' if name in required else '?') + ': ' + ts(value) for name, value in sorted(fields.items())]
        additional = schema.get('additionalProperties', True)
        if not fields:
            return 'Record<string, ' + ('never' if additional is False else ts(additional if isinstance(additional, dict) else {})) + '>'
        result = '{ ' + '; '.join(members) + ' }'
        if additional is not False:
            result += ' & Record<string, ' + ts(additional if isinstance(additional, dict) else {}) + '>'
        return result
    return 'unknown'


def content_type(contents):
    if not contents: return 'undefined'
    media = contents.get('application/json') or contents.get('multipart/form-data')
    if media is None:
        return 'string' if all(key.startswith('text/') for key in contents) else 'Blob'
    return ts(media.get('schema', {}))


def generate(schema):
    canonical = json.dumps(schema, ensure_ascii=False, sort_keys=True, indent=2, allow_nan=False) + '\n'
    fingerprint = hashlib.sha256(canonical.encode()).hexdigest()
    lines = ['// Generated by scripts/generate_rebuild_contracts.py. Do not edit.',
             '// Flexible JSON responses remain unknown/records; no invented response fields.',
             'export const OPENAPI_SHA256 = ' + literal(fingerprint) + ' as const', '', 'export interface Components {']
    for name, value in sorted(schema.get('components', {}).get('schemas', {}).items()):
        lines.append('  ' + literal(name) + ': ' + ts(value))
    lines.extend(['}', '', 'export interface Operations {'])
    for path, paths in sorted(schema['paths'].items()):
        key = path.removeprefix('/api/v1')
        lines.append('  ' + literal(key) + ': {')
        for method in METHODS:
            if method not in paths: continue
            operation = paths[method]
            response_types = sorted({content_type(value.get('content', {})) for code, value in operation.get('responses', {}).items() if str(code).startswith('2')})
            params = {}
            for value in paths.get('parameters', []) + operation.get('parameters', []):
                if value.get('in') == 'query': params[value['name']] = value
            query = ('{ ' + '; '.join(literal(name) + ('' if value.get('required') else '?') + ': ' + ts(value.get('schema', {})) for name, value in sorted(params.items())) + ' }'
                     if params else 'Record<string, never>')
            lines.append('    ' + literal(method) + ': { requestBody: ' + content_type(operation.get('requestBody', {}).get('content', {}))
                + '; response: ' + (' | '.join(response_types) or 'undefined') + '; query: ' + query + ' }')
        lines.append('  }')
    lines.extend(['}', '', 'export type ApiPath = keyof Operations',
        "export type ApiRequestBody<P extends ApiPath, M extends keyof Operations[P]> = Operations[P][M] extends { requestBody: infer B } ? B : never",
        "export type ApiResponse<P extends ApiPath, M extends keyof Operations[P]> = Operations[P][M] extends { response: infer R } ? R : never", ''])
    return canonical, '\n'.join(lines)


def snapshot():
    # No lifespan startup, database open, provider access, migration or workers.
    sys.path.insert(0, str(ROOT / 'backend'))
    with tempfile.TemporaryDirectory(prefix='trade-contracts-') as scratch:
        target = Path(scratch) / 'never-started'
        os.environ['TRADE_REBUILD_DATA_DIR'] = str(target)
        from trade_app.main import create_app
        schema = create_app(target).openapi()
        assert not target.exists(), 'Contract generation must not open application data'
    schema['paths'] = {key: value for key, value in schema['paths'].items() if key.startswith('/api/v1/') or key == '/health'}
    return schema


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    canonical, source = generate(snapshot())
    outputs = {ROOT / 'docs/api/openapi.generated.json': canonical,
               ROOT / 'frontend/src/rebuild/api-contracts.generated.ts': source}
    stale = []
    for path, value in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding='utf-8') != value: stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(value, encoding='utf-8', newline='\n')
    if stale:
        print('API contracts changed; regenerate and review: ' + ', '.join(stale), file=sys.stderr)
        return 1
    print('Trade OpenAPI and TypeScript contracts: ' + ('current' if args.check else 'generated'))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
